# static function

In [2]:
import numpy as np
a1= np.random.random((5,5))
a1=np.round(a1*100)# round off 
print(a1)

[[ 1. 84. 53. 51. 86.]
 [51. 24. 55.  9. 57.]
 [96. 87. 83. 80. 38.]
 [75. 60. 53. 90. 34.]
 [74. 95. 36. 18. 71.]]


# mean

In [3]:
np.mean( a1)


np.float64(58.44)

In [4]:
a1.mean()

np.float64(58.44)

# meadian 

In [5]:
np.median( a1, axis= 1)



array([53., 51., 83., 60., 71.])

01:04 MIN 

In [6]:
a2= np.random.random((5,5))
a2=np.round(a2*100)# round off 
print(a2)

[[33. 33. 57. 11.  6.]
 [54. 65. 59. 58. 88.]
 [97. 59. 46. 58. 99.]
 [ 3.  1. 72. 44. 40.]
 [84. 23. 57. 88. 10.]]


In [7]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# log and exponents

In [8]:
np.exp(a1)

array([[2.71828183e+00, 3.02507732e+36, 1.04137594e+23, 1.40934908e+22,
        2.23524660e+37],
       [1.40934908e+22, 2.64891221e+10, 7.69478527e+23, 8.10308393e+03,
        5.68572000e+24],
       [4.92345829e+41, 6.07603023e+37, 1.11286375e+36, 5.54062238e+34,
        3.18559318e+16],
       [3.73324200e+32, 1.14200739e+26, 1.04137594e+23, 1.22040329e+39,
        5.83461743e+14],
       [1.37338298e+32, 1.81123908e+41, 4.31123155e+15, 6.56599691e+07,
        6.83767123e+30]])

In [9]:
np.log(a1)

array([[0.        , 4.4308168 , 3.97029191, 3.93182563, 4.4543473 ],
       [3.93182563, 3.17805383, 4.00733319, 2.19722458, 4.04305127],
       [4.56434819, 4.46590812, 4.41884061, 4.38202663, 3.63758616],
       [4.31748811, 4.09434456, 3.97029191, 4.49980967, 3.52636052],
       [4.30406509, 4.55387689, 3.58351894, 2.89037176, 4.26267988]])

# round/floor/ceil

In [10]:
np.round(np.random.random((2,3))*100)

array([[ 0., 68., 35.],
       [40., 96., 46.]])

In [11]:
np.ceil(np.random.random((2,3))*100)

array([[67.,  9., 99.],
       [81., 37., 73.]])

In [12]:
np.floor(np.random.random((2,3))*100)

array([[68.,  5., 95.],
       [41., 85., 69.]])

In [13]:
a2= np.random.random((3,4))
a2=np.round(a2*100)# round off 
print(a2)
print('\n')
a1= np.random.random((10))
a1=np.round(a1*100)# round off 
print(a1)
print('\n')


[[90. 80. 62.  6.]
 [42. 92. 99. 72.]
 [73.  2. 54. 79.]]


[44.  2. 76. 18. 97. 37. 79. 50. 64.  3.]




In [14]:
a2

array([[90., 80., 62.,  6.],
       [42., 92., 99., 72.],
       [73.,  2., 54., 79.]])

In [15]:
print(a2[1,2]) # row column

99.0


In [16]:
a3= np.random.random((3,4,5)) # layer , # row  # column
a3=np.round(a3*100)# round off 
print(a3)

[[[ 42.  93.  82.  68.  12.]
  [ 71.  17.  22.  35.  41.]
  [ 60.  75.  87.  59.  96.]
  [ 71.  77.  85.  99.  21.]]

 [[ 26.  58.  46.  16.  14.]
  [ 58.  24. 100.  14.  57.]
  [ 69.  40.  25.  45.   5.]
  [  9.  53.  90.  62.  13.]]

 [[ 89.  97.  27.  26.  20.]
  [ 85.  95.  85.  30.  49.]
  [  9.   9.  22.  50.  82.]
  [ 68.  69.  47.  57.  66.]]]


In [17]:
print(a3[1,3,2])
print(a3[0,1,3])

90.0
35.0


# slicing

In [18]:
import numpy as np

In [19]:
a2= np.random.random((3,4))
a2=np.round(a2*100)# round off 
print(a2)
print('\n')
a1= np.random.random((10))
a1=np.round(a1*100)# round off 
print(a1)
print('\n')

[[59.  1. 93. 20.]
 [90. 89. 11. 17.]
 [52. 20. 34. 69.]]


[40. 20. 99. 85. 60. 92. 95. 64. 87. 58.]




In [20]:
a2

array([[59.,  1., 93., 20.],
       [90., 89., 11., 17.],
       [52., 20., 34., 69.]])

In [21]:
a2[ : , :  ]

array([[59.,  1., 93., 20.],
       [90., 89., 11., 17.],
       [52., 20., 34., 69.]])

In [54]:
a1

array([40., 20., 99., 85., 60., 92., 95., 64., 87., 58.])

In [22]:
a1[1:-1]

array([20., 99., 85., 60., 92., 95., 64., 87.])

In [23]:
a2

array([[59.,  1., 93., 20.],
       [90., 89., 11., 17.],
       [52., 20., 34., 69.]])

In [24]:
a2[0,:]

array([59.,  1., 93., 20.])

In [25]:
a2[:,2]

array([93., 11., 34.])

In [26]:
a2[0:2,] # row onward

array([[59.,  1., 93., 20.],
       [90., 89., 11., 17.]])

In [27]:
a2[1:, 1:3] # row onward : colums

array([[89., 11.],
       [20., 34.]])

In [55]:
a2

array([[59.,  1., 93., 20.],
       [90., 89., 11., 17.],
       [52., 20., 34., 69.]])

In [56]:
a2[1:2, 2:4]

array([[11., 17.]])

In [29]:
a2[ : :2,:  :  2] # row start : rown end  : step up col :: step up

array([[59., 93.],
       [52., 34.]])

In [30]:
a2[ 0: :2, 1 :   :  2]

array([[ 1., 20.],
       [20., 69.]])

In [31]:
a2[1:2:, : :3]

array([[90., 17.]])

In [32]:
a2[0:2:,1:5:]  

array([[ 1., 93., 20.],
       [89., 11., 17.]])

a2[ : :2,:  :  2]

# 3D slicing 


In [58]:
import numpy as np
arr = np.arange(36).reshape(4,3,3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]


In [60]:
arr[0:4:2] # 1 ek ek skip hoga 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [62]:
import numpy as np
arr5 = np.arange(45).reshape(5,3,3)
print(arr5)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]]


In [63]:
arr5[0:5:3] # 0 and 3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [33]:
a3

array([[[ 42.,  93.,  82.,  68.,  12.],
        [ 71.,  17.,  22.,  35.,  41.],
        [ 60.,  75.,  87.,  59.,  96.],
        [ 71.,  77.,  85.,  99.,  21.]],

       [[ 26.,  58.,  46.,  16.,  14.],
        [ 58.,  24., 100.,  14.,  57.],
        [ 69.,  40.,  25.,  45.,   5.],
        [  9.,  53.,  90.,  62.,  13.]],

       [[ 89.,  97.,  27.,  26.,  20.],
        [ 85.,  95.,  85.,  30.,  49.],
        [  9.,   9.,  22.,  50.,  82.],
        [ 68.,  69.,  47.,  57.,  66.]]])

In [57]:
a3[0:3:1]

array([[[ 42.,  93.,  82.,  68.,  12.],
        [ 71.,  17.,  22.,  35.,  41.],
        [ 60.,  75.,  87.,  59.,  96.],
        [ 71.,  77.,  85.,  99.,  21.]],

       [[ 26.,  58.,  46.,  16.,  14.],
        [ 58.,  24., 100.,  14.,  57.],
        [ 69.,  40.,  25.,  45.,   5.],
        [  9.,  53.,  90.,  62.,  13.]],

       [[ 89.,  97.,  27.,  26.,  20.],
        [ 85.,  95.,  85.,  30.,  49.],
        [  9.,   9.,  22.,  50.,  82.],
        [ 68.,  69.,  47.,  57.,  66.]]])

In [34]:
a3[0:3:2]

array([[[42., 93., 82., 68., 12.],
        [71., 17., 22., 35., 41.],
        [60., 75., 87., 59., 96.],
        [71., 77., 85., 99., 21.]],

       [[89., 97., 27., 26., 20.],
        [85., 95., 85., 30., 49.],
        [ 9.,  9., 22., 50., 82.],
        [68., 69., 47., 57., 66.]]])

In [35]:
a3[0:1:, 1:2:]

array([[[71., 17., 22., 35., 41.]]])

In [36]:
a3

array([[[ 42.,  93.,  82.,  68.,  12.],
        [ 71.,  17.,  22.,  35.,  41.],
        [ 60.,  75.,  87.,  59.,  96.],
        [ 71.,  77.,  85.,  99.,  21.]],

       [[ 26.,  58.,  46.,  16.,  14.],
        [ 58.,  24., 100.,  14.,  57.],
        [ 69.,  40.,  25.,  45.,   5.],
        [  9.,  53.,  90.,  62.,  13.]],

       [[ 89.,  97.,  27.,  26.,  20.],
        [ 85.,  95.,  85.,  30.,  49.],
        [  9.,   9.,  22.,  50.,  82.],
        [ 68.,  69.,  47.,  57.,  66.]]])

In [37]:
a3[1:2:, 0:4:,2:3:] # layer # Row # column

array([[[ 46.],
        [100.],
        [ 25.],
        [ 90.]]])

In [38]:
a3

array([[[ 42.,  93.,  82.,  68.,  12.],
        [ 71.,  17.,  22.,  35.,  41.],
        [ 60.,  75.,  87.,  59.,  96.],
        [ 71.,  77.,  85.,  99.,  21.]],

       [[ 26.,  58.,  46.,  16.,  14.],
        [ 58.,  24., 100.,  14.,  57.],
        [ 69.,  40.,  25.,  45.,   5.],
        [  9.,  53.,  90.,  62.,  13.]],

       [[ 89.,  97.,  27.,  26.,  20.],
        [ 85.,  95.,  85.,  30.,  49.],
        [  9.,   9.,  22.,  50.,  82.],
        [ 68.,  69.,  47.,  57.,  66.]]])

In [39]:
a3[0:4:2, 0::4,  0:5:4] # layer # Row # column

array([[[42., 12.]],

       [[89., 20.]]])

In [40]:
a1
for i in a1:
  print(i)

40.0
20.0
99.0
85.0
60.0
92.0
95.0
64.0
87.0
58.0


In [41]:
a2

array([[59.,  1., 93., 20.],
       [90., 89., 11., 17.],
       [52., 20., 34., 69.]])

In [42]:
for i in a2:
  print(i)

[59.  1. 93. 20.]
[90. 89. 11. 17.]
[52. 20. 34. 69.]


In [43]:
a3

array([[[ 42.,  93.,  82.,  68.,  12.],
        [ 71.,  17.,  22.,  35.,  41.],
        [ 60.,  75.,  87.,  59.,  96.],
        [ 71.,  77.,  85.,  99.,  21.]],

       [[ 26.,  58.,  46.,  16.,  14.],
        [ 58.,  24., 100.,  14.,  57.],
        [ 69.,  40.,  25.,  45.,   5.],
        [  9.,  53.,  90.,  62.,  13.]],

       [[ 89.,  97.,  27.,  26.,  20.],
        [ 85.,  95.,  85.,  30.,  49.],
        [  9.,   9.,  22.,  50.,  82.],
        [ 68.,  69.,  47.,  57.,  66.]]])

# transpose 

In [44]:
a2

array([[59.,  1., 93., 20.],
       [90., 89., 11., 17.],
       [52., 20., 34., 69.]])

In [45]:
a2.T

array([[59., 90., 52.],
       [ 1., 89., 20.],
       [93., 11., 34.],
       [20., 17., 69.]])

# ravel 
convert the any n-d array in 1 D 

In [46]:
a2.ravel()

array([59.,  1., 93., 20., 90., 89., 11., 17., 52., 20., 34., 69.])

# stacking 
 * needed to shap same

In [47]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4, a5

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [48]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [49]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# split needed to in equal part

In [50]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [52]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [53]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]