### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

In [2]:
import numpy as np

In [37]:
a= np.array([1,2,3,4])
print(a)
print(type(a))
print(a[0])

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [38]:
b = np.array([
            [1,2,3],
            [4,5,6]
            ])
print(b)
print(b[0][1])

[[1 2 3]
 [4 5 6]]
2


In [39]:
array3D= np.array(
    [[
    [ 1 , 2 , 3 ], 
    [ 4 , 5 , 6 ],
    [ 7 , 8 , 9]
    ]
    ,
    [
    [ 11 , 12 , 13 ], 
    [ 14 , 15 , 16 ],
    [ 17 , 18 , 19]
    ],
    
    
    ] )
print(array3D)
print(array3D.shape)
print(array3D[1][1][1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
(2, 3, 3)
15


In [40]:
array3D= np.array(
    [[
    [ 1 , 2 , 3 ], 
    [ 4 , 5 , 6 ],
    [ 7 , 8 , 9]
    ]
    ,
    [
    [ 11 , 12 , 13 ], 
    [ 14 , 15 , 16 ],
    [ 17 , 18 , 19]
    ],
    [
    [ 211 , 212 , 213 ], 
    [ 214 , 215 , 216 ],
    [ 217 , 218 , 219]
    ],
    
    
    ] )
print(array3D)
print(array3D.shape)
print(array3D.shape)
print(array3D[2][1][2])   # layer of 3d , row of columsn , col 

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 11  12  13]
  [ 14  15  16]
  [ 17  18  19]]

 [[211 212 213]
  [214 215 216]
  [217 218 219]]]
(3, 3, 3)
(3, 3, 3)
216


# 4d array

In [41]:
array3D= np.array(
[[[
    [ 1 , 2 , 3 ], 
    [ 4 , 5 , 6 ],
    [ 7 , 8 , 9]
    ]
    ,
    [
    [ 11 , 12 , 13 ], 
    [ 14 , 15 , 16 ],
    [ 17 , 18 , 19],],] , # 3d array 

[
  [
    [ 1 , 2 , 3 ], 
    [ 4 , 5 , 6 ],
    [ 7 , 8 , 9]
    ]
    ,
    [
    [ 11 , 12 , 13 ], 
    [ 14 , 15 , 16 ],
    [ 17 , 18 , 19],],],]






    
)
print(array3D)
print(array3D.shape)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[11 12 13]
   [14 15 16]
   [17 18 19]]]


 [[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[11 12 13]
   [14 15 16]
   [17 18 19]]]]
(2, 2, 3, 3)


# fectchin item 

# there data type 

In [42]:
a= np.array([1,2,3,4],dtype=float)
a

array([1., 2., 3., 4.])

In [43]:
a= np.array([1,2,3,4],dtype=bool)
a

array([ True,  True,  True,  True])

# Arange--> as simple as range 


In [44]:
a = np.arange(0,10,2) # start stop jump
a

array([0, 2, 4, 6, 8])

# reshape

In [45]:
az

NameError: name 'az' is not defined

In [ ]:
aaz = np.arange(2).reshape(2) # row *  col 
az

array([0, 1])

In [ ]:
az = np.arange(4).reshape(2,2) # row *  col 
az

array([[0, 1],
       [2, 3]])

In [ ]:
az = np.arange(8).reshape(2,2,2) # row *  col 
az

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
az = np.arange(16).reshape(2,2,2,2) # row *  col 
az

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
az = np.arange(32).reshape(2,2,2,2,2) # 3 d block , layer of 3d , row , col 
az

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [ ]:
a = np.arange(0,100,2).reshape(5,10)

In [ ]:
a= np.ones((3,5),dtype=int)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a= np.zeros((3,5),dtype=int)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
a= np.random.random((3,5))
a

array([[0.30101426, 0.02531002, 0.51313697, 0.19550269, 0.06245559],
       [0.98491858, 0.3262546 , 0.97445584, 0.94723276, 0.0953138 ],
       [0.60790691, 0.57870766, 0.60649535, 0.84087922, 0.08336538]])

In [ ]:
# np.linspce
a= np.linspace(10,50,5)
a

array([10., 20., 30., 40., 50.])

# idendlty

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# array attributes

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3  = np.arange(8).reshape(2,2,2)
print(a1,end= "\n" )
print(end= "\n")
print(a2,end= "\n")
print(end= "\n")


print(a3 )

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


# ndim  
 * no of dimension

In [ ]:
a2.ndim 

2

In [ ]:
a3.ndim # row

3

In [ ]:
az.ndim

4

# shape

In [ ]:
a1.shape

(10,)

In [ ]:
a2.shape

(3, 4)

In [ ]:
az.shape

(2, 2, 2, 2)

# size


In [ ]:
az.size

16

# item size


In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a2.itemsize # its is in byte

8

# Dtype 

In [ ]:
a2.dtype

dtype('float64')

# chainging dtype

In [ ]:
a2.astype(int)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(a3.astype(int))
print(a3.astype(bool))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[False  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]]


# astype 
--> will convert the data into other one ( to save some memory)

In [ ]:
print(a1.astype(np.int32))

[0 1 2 3 4 5 6 7 8 9]


#  scaler operation

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
a1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a1+99

array([ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108])

# check realtionship 
sure i don't have
>,<,= == != 

In [ ]:
am
am> 0


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

# vector operation

In [ ]:
a1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a2  = a2 + a2
a2

array([[ 0.,  4.,  8., 12.],
       [16., 20., 24., 28.],
       [32., 36., 40., 44.]])

# Mathmatic function

In [1]:
np.max( a2)

NameError: name 'np' is not defined

In [ ]:
np.min( a2)

np.float64(0.0)

In [ ]:
np.prod( a2)

np.float64(0.0)

# you can ask the  maxium number in any row 


In [3]:
a1= np.random.random((5,5))

print(a1)

print(end="\n")

a1=np.round(a1*100)# round off 
print(a1)

[[0.28677092 0.70019537 0.81510751 0.37234297 0.97157002]
 [0.18810614 0.56676134 0.20260267 0.58123656 0.27066058]
 [0.33117837 0.00882724 0.04320586 0.48993187 0.00678166]
 [0.92048589 0.15087594 0.48245456 0.03596414 0.01359844]
 [0.51172971 0.17123083 0.18522039 0.59555436 0.81534246]]

[[29. 70. 82. 37. 97.]
 [19. 57. 20. 58. 27.]
 [33.  1.  4. 49.  1.]
 [92. 15. 48.  4.  1.]
 [51. 17. 19. 60. 82.]]


In [4]:
np.max(a1, axis = 0)
# col = 0  and row = 1

array([92., 70., 82., 60., 97.])

In [5]:
np.max(a1, axis = 1)

array([97., 58., 49., 92., 82.])

# Time stamp--> 1:03:51 min

In [6]:
np.max(a1)

np.float64(97.0)