
# Numpy array vs Python lists

In [29]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time
start = time .time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)

2.210538625717163


In [30]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.17281126976013184


# Here we can say that numpy is faster than python lists
* 1.462 vs 0.0892

# how much faster
in my case its 16 times faster

In [31]:
1.4621992111206055/0.08923482894897461

16.385969787163553

# memory usage

# python

In [32]:
a = [i for i in range (10000000)]
import sys
sys.getsizeof(a)

89095160

In [33]:
a = np.arange(10000000, dtype = np.int8)
sys.getsizeof(a)

10000112

# convenience

### Advanced Indexing

In [34]:
# Normal Indexing and slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
a[1,2]

np.int64(6)

In [36]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [37]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#  fancy index 
 *  jo chaiey wo pass 
 *

In [38]:
a[[0,2,3,4]] # rows passed

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [39]:
a= np.arange(24).reshape(6,4)


In [40]:
a
a[[0,1,4,5]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
a[:,[0,2,3]] 

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [43]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[62, 45, 83, 28],
       [67,  6, 38, 21],
       [71, 75, 30, 93],
       [52, 43, 23, 89],
       [ 3, 18, 16, 72],
       [75, 83, 45, 34]], dtype=int32)

it will pull out only which are based on the condition 

boolean array 
mask over orinal array 

In [44]:
a>50

array([[ True, False,  True, False],
       [ True, False, False, False],
       [ True,  True, False,  True],
       [ True, False, False,  True],
       [False, False, False,  True],
       [ True,  True, False, False]])

In [45]:
# masked 
a[a > 50]


array([62, 83, 67, 71, 75, 93, 52, 89, 72, 75, 83], dtype=int32)

In [46]:
# find out even numbers
a[a % 2 == 0]

array([62, 28,  6, 38, 30, 52, 18, 16, 72, 34], dtype=int32)

In [47]:
# find all numbers greater than 50 and are even
# and  this and is logical and which will not use here 
# & this will be used here 
# why --> we are working with boolean operatoro 

a[(a > 50) & (a % 2 == 0)]

array([62, 52, 72], dtype=int32)

In [48]:
# find all numbers not divisible by 7
# ~ not operator    will invert the value 
# 0-->1
# 1-->0
a[~(a % 7 == 0)]

array([62, 45, 83, 67,  6, 38, 71, 75, 30, 93, 52, 43, 23, 89,  3, 18, 16,
       72, 75, 83, 45, 34], dtype=int32)

## Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

# same shape


In [49]:
a = np.random.randint(1,1000,24).reshape(6,4)
b = np.random.randint(1,1000,24).reshape(6,4)

In [50]:
a

array([[137, 815, 320, 896],
       [335, 530,  17, 855],
       [509, 887, 558, 251],
       [660, 102, 503, 397],
       [916, 636, 306, 622],
       [448, 598, 115, 135]], dtype=int32)

In [51]:
b

array([[726, 561, 594, 939],
       [509,  59, 786, 507],
       [204, 119, 496, 110],
       [ 79, 746, 508, 542],
       [777, 945, 814, 339],
       [906, 543, 109, 879]], dtype=int32)

In [52]:
c= a + b
c

array([[ 863, 1376,  914, 1835],
       [ 844,  589,  803, 1362],
       [ 713, 1006, 1054,  361],
       [ 739,  848, 1011,  939],
       [1693, 1581, 1120,  961],
       [1354, 1141,  224, 1014]], dtype=int32)

# diffrent shape 

In [53]:
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

a_b = a+b
a_b 

array([[0, 2, 4],
       [3, 5, 7]])

#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

### this will work cause   

- this is due b can be   
        * b and b column number matched    
        * b can be strected 1,3 --> 2,3 ,3--> 3
        * so after finaly 4,3  (b " 4,3) can be matched 

In [54]:
# More examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


not cols didnot matched due to this can't be formed

need to strech

In [56]:
# More examples

a = np.arange(12).reshape(4,4)
b = np.arange(3)

print(a)
print(b)

print(a+b)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [57]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)
 
print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1) 

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [58]:
a = np.arange(4).reshape(2,1)
 # if there  could 2--> 1 then it can be done
b = np.arange(4).reshape(4,1) 

print(a)
print(b)

print(a + b)

ValueError: cannot reshape array of size 4 into shape (2,1)