# static function

In [1]:
import numpy as np
a1= np.random.random((5,5))
a1=np.round(a1*100)# round off 
print(a1)

[[81. 69. 59. 67. 77.]
 [54. 23. 42. 19. 35.]
 [17. 57. 67. 49. 86.]
 [67. 82. 14. 69. 50.]
 [86. 38. 64. 16. 65.]]


# mean

In [2]:
np.mean( a1)


np.float64(54.12)

In [3]:
a1.mean()

np.float64(54.12)

# meadian 

In [4]:
np.median( a1, axis= 1)



array([69., 35., 57., 67., 64.])

01:04 MIN 

In [5]:
a2= np.random.random((5,5))
a2=np.round(a2*100)# round off 
print(a2)

[[59. 61. 18. 56. 84.]
 [ 3. 70. 58. 36. 82.]
 [83. 77. 85.  7. 93.]
 [83. 22. 54. 52. 13.]
 [33. 19. 99. 56. 59.]]


In [6]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# log and exponents

In [7]:
np.exp(a1)

array([[1.50609731e+35, 9.25378173e+29, 4.20121040e+25, 1.25236317e+29,
        2.75851345e+33],
       [2.83075330e+23, 9.74480345e+09, 1.73927494e+18, 1.78482301e+08,
        1.58601345e+15],
       [2.41549528e+07, 5.68572000e+24, 1.25236317e+29, 1.90734657e+21,
        2.23524660e+37],
       [1.25236317e+29, 4.09399696e+35, 1.20260428e+06, 9.25378173e+29,
        5.18470553e+21],
       [2.23524660e+37, 3.18559318e+16, 6.23514908e+27, 8.88611052e+06,
        1.69488924e+28]])

In [8]:
np.log(a1)

array([[4.39444915, 4.2341065 , 4.07753744, 4.20469262, 4.34380542],
       [3.98898405, 3.13549422, 3.73766962, 2.94443898, 3.55534806],
       [2.83321334, 4.04305127, 4.20469262, 3.8918203 , 4.4543473 ],
       [4.20469262, 4.40671925, 2.63905733, 4.2341065 , 3.91202301],
       [4.4543473 , 3.63758616, 4.15888308, 2.77258872, 4.17438727]])

# round/floor/ceil

In [9]:
np.round(np.random.random((2,3))*100)

array([[20., 75., 31.],
       [74., 72., 49.]])

In [10]:
np.ceil(np.random.random((2,3))*100)

array([[23., 75.,  2.],
       [51., 12., 95.]])

In [11]:
np.floor(np.random.random((2,3))*100)

array([[97., 81., 40.],
       [51., 50., 25.]])

In [ ]:
a2= np.random.random((3,4))
a2=np.round(a2*100)# round off 
print(a2)
print('\n')
a1= np.random.random((10))
a1=np.round(a1*100)# round off 
print(a1)
print('\n')


[[42. 59. 74. 40.]
 [42. 82. 27.  9.]
 [52. 46. 99. 71.]]


[44.  6.  2.  6. 84. 68. 15. 36. 28. 55.]


[[[92. 67.  0. 84.]
  [29. 76. 84. 30.]
  [ 6. 35. 19. 23.]
  [97. 38. 54.  7.]]

 [[31.  5. 46. 64.]
  [ 6. 40. 10. 45.]
  [72. 15. 14. 99.]
  [37. 30. 75. 60.]]

 [[80. 99. 91. 25.]
  [58. 55. 81. 83.]
  [29. 91. 17. 10.]
  [ 3. 26. 18. 47.]]

 [[ 6. 57. 73. 23.]
  [39. 32. 30. 89.]
  [78. 41. 28. 99.]
  [59.  2. 76. 88.]]]


In [28]:
a2

array([[42., 59., 74., 40.],
       [42., 82., 27.,  9.],
       [52., 46., 99., 71.]])

In [29]:
print(a2[1,2]) # row column

27.0


In [34]:
a3= np.random.random((2,4,5)) # layer , # row  # column
a3=np.round(a3*100)# round off 
print(a3)

[[[19. 71. 98. 83. 17.]
  [36. 12. 57.  1. 33.]
  [19. 91. 44. 16. 59.]
  [ 8.  3. 44.  9. 32.]]

 [[83. 40. 37. 73. 26.]
  [17. 99. 47. 59. 44.]
  [12. 82. 16. 58. 24.]
  [12. 85. 70. 60. 77.]]]


In [38]:
print(a3[1,3,2])
print(a3[0,1,3])

70.0
1.0
