# static function

In [41]:
import numpy as np
a1= np.random.random((5,5))
a1=np.round(a1*100)# round off 
print(a1)

[[18. 45. 83. 87. 98.]
 [72. 35. 61. 12. 81.]
 [67. 67. 23. 37. 26.]
 [37. 51. 61.  1. 86.]
 [50. 34. 68. 69. 92.]]


# mean

In [42]:
np.mean( a1)


np.float64(54.44)

In [43]:
a1.mean()

np.float64(54.44)

# meadian 

In [44]:
np.median( a1, axis= 1)



array([83., 61., 37., 51., 68.])

01:04 MIN 

In [45]:
a2= np.random.random((5,5))
a2=np.round(a2*100)# round off 
print(a2)

[[ 9. 69. 89.  8. 32.]
 [45.  5. 69. 33. 43.]
 [90. 75. 61. 36. 27.]
 [66. 34. 66. 30. 44.]
 [33. 91. 16. 88. 46.]]


In [46]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# log and exponents

In [47]:
np.exp(a1)

array([[6.56599691e+07, 3.49342711e+19, 1.11286375e+36, 6.07603023e+37,
        3.63797095e+42],
       [1.85867175e+31, 1.58601345e+15, 3.10429794e+26, 1.62754791e+05,
        1.50609731e+35],
       [1.25236317e+29, 1.25236317e+29, 9.74480345e+09, 1.17191424e+16,
        1.95729609e+11],
       [1.17191424e+16, 1.40934908e+22, 3.10429794e+26, 2.71828183e+00,
        2.23524660e+37],
       [5.18470553e+21, 5.83461743e+14, 3.40427605e+29, 9.25378173e+29,
        9.01762841e+39]])

In [48]:
np.log(a1)

array([[2.89037176, 3.80666249, 4.41884061, 4.46590812, 4.58496748],
       [4.27666612, 3.55534806, 4.11087386, 2.48490665, 4.39444915],
       [4.20469262, 4.20469262, 3.13549422, 3.61091791, 3.25809654],
       [3.61091791, 3.93182563, 4.11087386, 0.        , 4.4543473 ],
       [3.91202301, 3.52636052, 4.21950771, 4.2341065 , 4.52178858]])

# round/floor/ceil

In [49]:
np.round(np.random.random((2,3))*100)

array([[82., 91., 84.],
       [65., 27., 90.]])

In [50]:
np.ceil(np.random.random((2,3))*100)

array([[10., 31., 72.],
       [39., 69., 91.]])

In [51]:
np.floor(np.random.random((2,3))*100)

array([[56., 90., 20.],
       [98., 46., 60.]])

In [52]:
a2= np.random.random((3,4))
a2=np.round(a2*100)# round off 
print(a2)
print('\n')
a1= np.random.random((10))
a1=np.round(a1*100)# round off 
print(a1)
print('\n')


[[88. 23. 36. 58.]
 [92. 43.  3. 76.]
 [12. 73. 14. 35.]]


[28. 21. 93. 86. 61.  8. 66. 47. 73. 89.]




In [53]:
a2

array([[88., 23., 36., 58.],
       [92., 43.,  3., 76.],
       [12., 73., 14., 35.]])

In [54]:
print(a2[1,2]) # row column

3.0


In [55]:
a3= np.random.random((3,4,5)) # layer , # row  # column
a3=np.round(a3*100)# round off 
print(a3)

[[[76. 57. 51. 42. 36.]
  [83. 37. 97. 82. 40.]
  [69. 47. 21. 99. 91.]
  [45. 30. 60. 58. 75.]]

 [[23. 40. 18. 60. 25.]
  [64. 15. 10. 33. 79.]
  [38. 78. 76. 60. 30.]
  [72. 66. 18. 91. 26.]]

 [[17.  1. 52. 43. 78.]
  [23. 94. 68. 55. 21.]
  [89. 40.  5. 67. 89.]
  [94. 31. 42. 46. 15.]]]


In [56]:
print(a3[1,3,2])
print(a3[0,1,3])

18.0
82.0


# slicing

In [57]:
a1

array([28., 21., 93., 86., 61.,  8., 66., 47., 73., 89.])

In [58]:
a1[1:-1]

array([21., 93., 86., 61.,  8., 66., 47., 73.])

In [59]:
a2

array([[88., 23., 36., 58.],
       [92., 43.,  3., 76.],
       [12., 73., 14., 35.]])

In [60]:
a2[0,:]

array([88., 23., 36., 58.])

In [61]:
a2[:,2]

array([36.,  3., 14.])

In [62]:
a2[0:2,] # row onward

array([[88., 23., 36., 58.],
       [92., 43.,  3., 76.]])

In [63]:
a2[1:, 1:3] # row onward : colums

array([[43.,  3.],
       [73., 14.]])

In [64]:
a2

array([[88., 23., 36., 58.],
       [92., 43.,  3., 76.],
       [12., 73., 14., 35.]])

In [ ]:
a2[ : :2,:  :  2] # row start : rown end  : step up col :: step up

array([[88., 36.],
       [12., 14.]])

In [66]:
a2[ 0: :2, 1 :   :  2]

array([[23., 58.],
       [73., 35.]])

In [76]:
a2[1:2:, : :3]

array([[92., 76.]])

In [ ]:
a2[0:2:,1:5:]  

array([[23., 36., 58.],
       [43.,  3., 76.]])

a2[ : :2,:  :  2]

In [80]:
a3

array([[[76., 57., 51., 42., 36.],
        [83., 37., 97., 82., 40.],
        [69., 47., 21., 99., 91.],
        [45., 30., 60., 58., 75.]],

       [[23., 40., 18., 60., 25.],
        [64., 15., 10., 33., 79.],
        [38., 78., 76., 60., 30.],
        [72., 66., 18., 91., 26.]],

       [[17.,  1., 52., 43., 78.],
        [23., 94., 68., 55., 21.],
        [89., 40.,  5., 67., 89.],
        [94., 31., 42., 46., 15.]]])

In [82]:
a3[0:3:2]

array([[[76., 57., 51., 42., 36.],
        [83., 37., 97., 82., 40.],
        [69., 47., 21., 99., 91.],
        [45., 30., 60., 58., 75.]],

       [[17.,  1., 52., 43., 78.],
        [23., 94., 68., 55., 21.],
        [89., 40.,  5., 67., 89.],
        [94., 31., 42., 46., 15.]]])

In [86]:
a3[0:1:, 1:2:]

array([[[83., 37., 97., 82., 40.]]])

In [88]:
a3

array([[[76., 57., 51., 42., 36.],
        [83., 37., 97., 82., 40.],
        [69., 47., 21., 99., 91.],
        [45., 30., 60., 58., 75.]],

       [[23., 40., 18., 60., 25.],
        [64., 15., 10., 33., 79.],
        [38., 78., 76., 60., 30.],
        [72., 66., 18., 91., 26.]],

       [[17.,  1., 52., 43., 78.],
        [23., 94., 68., 55., 21.],
        [89., 40.,  5., 67., 89.],
        [94., 31., 42., 46., 15.]]])

In [98]:
a3[1:2:, 0:4:,2:3:] # layer # Row # column

array([[[18.],
        [10.],
        [76.],
        [18.]]])

In [93]:
a3

array([[[76., 57., 51., 42., 36.],
        [83., 37., 97., 82., 40.],
        [69., 47., 21., 99., 91.],
        [45., 30., 60., 58., 75.]],

       [[23., 40., 18., 60., 25.],
        [64., 15., 10., 33., 79.],
        [38., 78., 76., 60., 30.],
        [72., 66., 18., 91., 26.]],

       [[17.,  1., 52., 43., 78.],
        [23., 94., 68., 55., 21.],
        [89., 40.,  5., 67., 89.],
        [94., 31., 42., 46., 15.]]])

In [105]:
a3[0:4:2, 0::4,  0:5:4] # layer # Row # column

array([[[76., 36.]],

       [[17., 78.]]])

In [68]:
a1
for i in a1:
  print(i)

28.0
21.0
93.0
86.0
61.0
8.0
66.0
47.0
73.0
89.0


In [69]:
a2

array([[88., 23., 36., 58.],
       [92., 43.,  3., 76.],
       [12., 73., 14., 35.]])

In [70]:
for i in a2:
  print(i)

[88. 23. 36. 58.]
[92. 43.  3. 76.]
[12. 73. 14. 35.]


In [71]:
a3

array([[[76., 57., 51., 42., 36.],
        [83., 37., 97., 82., 40.],
        [69., 47., 21., 99., 91.],
        [45., 30., 60., 58., 75.]],

       [[23., 40., 18., 60., 25.],
        [64., 15., 10., 33., 79.],
        [38., 78., 76., 60., 30.],
        [72., 66., 18., 91., 26.]],

       [[17.,  1., 52., 43., 78.],
        [23., 94., 68., 55., 21.],
        [89., 40.,  5., 67., 89.],
        [94., 31., 42., 46., 15.]]])

# transpose 

In [106]:
a2

array([[88., 23., 36., 58.],
       [92., 43.,  3., 76.],
       [12., 73., 14., 35.]])

In [107]:
a2.T

array([[88., 92., 12.],
       [23., 43., 73.],
       [36.,  3., 14.],
       [58., 76., 35.]])

# ravel 
convert the any n-d array in 1 D 

In [108]:
a2.ravel()

array([88., 23., 36., 58., 92., 43.,  3., 76., 12., 73., 14., 35.])

# stacking 
 * needed to shap same

In [111]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4, a5

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [113]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [114]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# split needed to in equal part

In [116]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [118]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [121]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]