### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

In [43]:
import numpy as np

In [44]:
a= np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [45]:
b = np.array([
            [1,2,3],
            [4,5,6]
            ])
print(b)

[[1 2 3]
 [4 5 6]]


In [46]:
array3D= np.array(
    [[
    [ 1 , 2 , 3 ], 
    [ 4 , 5 , 6 ],
    [ 7 , 8 , 9]
    ]] )
print(array3D)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


# there data type 

In [47]:
a= np.array([1,2,3,4],dtype=float)
a

array([1., 2., 3., 4.])

In [48]:
a= np.array([1,2,3,4],dtype=bool)
a

array([ True,  True,  True,  True])

# Arange--> as simple as range 


In [49]:
a = np.arange(0,10,2) # start stop jump
a

array([0, 2, 4, 6, 8])

# reshape

In [69]:
az = np.arange(0,16,1).reshape(2,2,2,2) # row *  col 
a

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [70]:
a = np.arange(0,100,2).reshape(5,10)

In [71]:
a= np.ones((3,5),dtype=int)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [72]:
a= np.zeros((3,5),dtype=int)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [73]:
a= np.random.random((3,5))
a

array([[0.30101426, 0.02531002, 0.51313697, 0.19550269, 0.06245559],
       [0.98491858, 0.3262546 , 0.97445584, 0.94723276, 0.0953138 ],
       [0.60790691, 0.57870766, 0.60649535, 0.84087922, 0.08336538]])

In [74]:
# np.linspce
a= np.linspace(10,50,5)
a

array([10., 20., 30., 40., 50.])

# idendlty

In [75]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# array attributes

In [76]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3  = np.arange(8).reshape(2,2,2)
print(a1,end= "\n" )
print(end= "\n")
print(a2,end= "\n")
print(end= "\n")


print(a3 )

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


# ndim  
 * no of dimension

In [77]:
a2.ndim 

2

In [78]:
a3.ndim # row

3

In [79]:
az.ndim

4

# shape

In [80]:
a1.shape

(10,)

In [81]:
a2.shape

(3, 4)

In [82]:
az.shape

(2, 2, 2, 2)

# size


In [83]:
az.size

16

# item size


In [85]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [86]:
a2.itemsize # its is in byte

8

# Dtype 

In [87]:
a2.dtype

dtype('float64')

# chainging dtype

In [88]:
a2.astype(int)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
print(a3.astype(int))
print(a3.astype(bool))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[False  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]]


# astype 
--> will convert the data into other one ( to save some memory)

In [ ]:
print(a1.astype(np.int32))

[0 1 2 3 4 5 6 7 8 9]


#  scaler operation

In [96]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
a1**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [98]:
a1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [99]:
a1+99

array([ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108])

# check realtionship 
sure i don't have
>,<,= == != 

In [ ]:
am=np.identity(3)
am> 0


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

# vector operation

In [105]:
a1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [108]:
a2  = a2 + a2
a2

array([[ 0.,  4.,  8., 12.],
       [16., 20., 24., 28.],
       [32., 36., 40., 44.]])

# Mathmatic function

In [109]:
np.max( a2)

np.float64(44.0)

In [110]:
np.min( a2)

np.float64(0.0)

In [111]:
np.prod( a2)

np.float64(0.0)

# you can ask the  maxium number in any row 


In [117]:
a1= np.random.random((5,5))

print(a1)

print(end="\n")

a1=np.round(a1*100)# round off 
print(a1)

[[0.64713889 0.33524431 0.72647975 0.46890689 0.2090752 ]
 [0.09748087 0.50018295 0.71221385 0.92152365 0.10658709]
 [0.07607887 0.65425862 0.43247678 0.22897697 0.91726653]
 [0.53074064 0.68114086 0.15491038 0.9748891  0.43356979]
 [0.24757421 0.70810638 0.06430895 0.65059468 0.64336815]]

[[65. 34. 73. 47. 21.]
 [10. 50. 71. 92. 11.]
 [ 8. 65. 43. 23. 92.]
 [53. 68. 15. 97. 43.]
 [25. 71.  6. 65. 64.]]


In [119]:
np.max(a1, axis = 0)
# col = 0  and row = 1

array([65., 71., 73., 97., 92.])

In [120]:
np.max(a1, axis = 1)

array([73., 92., 92., 97., 71.])

# Time stamp--> 1:03:51 min