**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [142]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.
 
- null vector look like this 


- [0,0,0]
- [0,0,0]
- [0,0,0]


In [143]:
a = np.zeros((10))
a[3]=1
print(a)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [144]:
a = np.zeros((1,10))
a[0,3]=1
print(a)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


###`Q-2` Ask user to input two numbers a, b. 
- Write a program to generate a random array of shape (a, b)
- print the array and avg of the array.

In [145]:
d = np.random.randint(3, 11,size= (5,2))
d

array([[9, 9],
       [5, 6],
       [7, 6],
       [5, 7],
       [6, 8]], dtype=int32)

In [146]:
#Code here
a = 5 #int(input( "Enter the a "))
b = 5 #int(input( "Enter the b "))
arr = np.random.random( size=(5,4))*100
arr=np.average(arr)
print(arr)


55.15865185940034


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [147]:
#Code here
i = 5
j = 5
jj = np.zeros((i,j))
jj[ 0, : ] = 1 # oth column
jj[ : ,0 ]= 1
jj[-1, : ]=1
jj[ : , -1 ]=1




In [148]:
jj

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [149]:
#Code here
vec = np.linspace(0, 1, 12)[1:-1] #  

print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [150]:
#Code here
iden_matrix= np.ones((3,3)) 
iden_matrix[0, 1:3] = 0
iden_matrix[1, 0:3:2] = 0
iden_matrix[2, 0:2] = 0

iden_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [151]:
# Method 1: Direct identity
iden_matrix1 = np.eye(3)

# Method 2: Using fill diagonal
iden_matrix2 = np.zeros((3,3))
np.fill_diagonal(iden_matrix2, 1)

# print
print(iden_matrix1,end="\n")
print(iden_matrix2,end="\n")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

just in case if u want to use random 

In [152]:
#1D
f = np.random.randint(0, 7, size=(5))
f

array([2, 0, 6, 6, 6], dtype=int32)

In [153]:
# 2d
f = np.random.random((1,5))

# radom need size
- not reshape
- .randint(1, 501, size=5) range size

In [154]:
arr = np.random.random( size=5)*10
arr

array([6.20352064, 0.45629941, 1.62202189, 4.21335016, 6.85104109])

In [155]:
arr = np.random.randint(1, 501, size=5)
arr

array([379,  97,  81, 344,  53], dtype=int32)

In [156]:
#Code here
f = np.arange(0,5).reshape((1,5))
g = np.arange(0,5).reshape((1,5))
h = np.arange(0,5).reshape((1,5))
np.vstack((f,g,h))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```
##### √[(x₁-x₂)² + (y₁-y₂)²]


In [157]:
#code here
points = np.random.randint(1, 100, size=(10,2))
given_point=np.array([[10,2]])
distance = np.zeros((1,10))

for i in range(len(points)):
    distance[0,i] = (   ((  points[i,0]-distance[0,0])**2) +   ((points[i,1]-distance[0,1])**2  ))**0.5
distance

array([[100.12492197,  76.02970007,  63.62610671,  48.00392827,
         66.49128053,  22.59952238, 106.13757994,  77.61275805,
         57.32836853,  36.34244446]])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

### Formula:
- z = 99 % 8 = 3
- y = (99 // 8) % 7 = 12 % 7 = 5  
- x = (99 // 8) // 7 = 12 // 7 = 1

In [158]:
#Code here
ii=np.random.randint(1,500,size=(6,7,8))
print(ii,end= "\n")

print(ii[1,5,3])

[[[447 495 232  11 141 345 412 164]
  [218 327 325 124 201 414  70 232]
  [232  90 316  48 244 192  13 479]
  [467 177  66 122 370 429 250 381]
  [203 108  70 293 153 305  40 144]
  [251 299 196 384  90 140 330 110]
  [340 191 175 447 111 434 170 150]]

 [[123 480 224 186 382 303 161 221]
  [192 371 417 219 325 240 333  54]
  [326 216  41 119  78 160 170 397]
  [291 125 150 416 419 441 490 406]
  [369 328  44 136  53  35 153 282]
  [226 249 132 226 355 385 334 337]
  [212  96 419 199 325 116   7 388]]

 [[108 362 235 473 261 334  50  10]
  [ 82 325 453 295 228 487  76 220]
  [373 327 242   4 459 294 237 484]
  [362 416 343 353  11 311   3 257]
  [489 125 469  24 328 471  40 146]
  [255 417  18 155 179 423  85 202]
  [179  58 372 348 316 112 163 129]]

 [[ 97  58  28 106 407 188  78 435]
  [ 22 198 283 385 100 177 374 235]
  [437  85 118 339 188 450 463 156]
  [280 462 216  83  67 255 408 430]
  [308 482 200 108 397  25 497  21]
  [412 488 360 324 273 445 197  70]
  [339 466 252 207 451

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [159]:
#Code here
q9= np.array([1 ,2 ,3 ,4 ,-8 ,-10])
q9[::-1] # start , stop , step up 





array([-10,  -8,   4,   3,   2,   1])

In [160]:
b = np.array([
            [1,2,3],
            [4,5,6]
            ])
print(b)

b[0]=b[0, ::-1]
b[1]=b[1, ::-1]

b



[[1 2 3]
 [4 5 6]]


array([[3, 2, 1],
       [6, 5, 4]])

#### np.flip(arr)

In [161]:
print(np.flip(b))
print(np.flip(q9))

[[4 5 6]
 [1 2 3]]
[-10  -8   4   3   2   1]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [162]:
#Code here
a= np.array([1,2,3,4])
count =0
for i in range(len(a)):
    count = count+1
count



4

In [163]:
# 2d 
b = np.array([
            [1,2,3],
            [4,5,6],
            [4,5,6],
            ])
row,col=b.shape
print( row, end= '\n' )
print( col, end= '\n' )
count = 0 
for i in range(row):
    for j in range(col):
        count = count+1
print(count)


3
3
9


In [164]:
# Final version  
b=np.random.randint(1,500,size=(6,7,8))
b.shape
layer ,row ,col = b.shape
count = 0
for i in range(layer):
    for j in range(row):
        for k in range(col):
            count = count+1
print(count)


336


In [165]:
count = np.prod(b.shape)
count

np.int64(336)

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$
z
https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

- e^ = math.e 
- z = array input [1,2,3,4,5,6,7,8]
 
$${e^{z₁}+e^{z₂}+e^{z₃}} = {\sum_{j=i}^{K}{e^{z_j}}}$$


- squares = sum(i**2 for i in range(1, 6))  
- 

In [166]:
import math
math.e

2.718281828459045

In [167]:
#Code here
input_arr=np.array([86.03331084,37.7285648 , 48.64908087, 87.16563062, 38.40852563, 37.20006318])

exp_arr = np.array([math.e ** x for x in input_arr])
deno =sum(exp_arr)
print("exp_arr", exp_arr,end ="\n ")

print()
print("deno",deno, end="\n" )
print()

result = exp_arr / deno

print(result)




exp_arr [2.31095856e+37 2.42832887e+16 1.34284959e+21 7.17054870e+37
 4.79303653e+16 1.43146972e+16]
 
deno 9.481507261792594e+37

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


In [168]:
# exp_arr = np.array([math.e ** x for x in input_arr])
# exp_arr
exp_list = []
for x in input_arr:
    exp_list.append(math.e ** x)

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [169]:
a= np.array([[0 ,1, 2 ,3 ,4]
    ,[5 ,6 ,7 ,8 ,9]])
b= np.array([[0 ,1, 2 ,3 ,4]
    ,])
c = np.vstack((a,b))
print( a.shape)
print( b.shape)

dims = b.shape
dims

(2, 5)
(1, 5)


(1, 5)

#### *arrays 
- collects all arguments into a tuple

#### isinstance(arr, np.ndarray)
- Checks if 'arr' is a numpy array
-  Returns True if yes, False if no

In [170]:
def vertical_stack(*arrays): # * arrays --> collects all arguments into a tuple
    for arr in arrays:
        if not isinstance(arr, np.ndarray):
            raise TypeError("All inputs must be numpy arrays")
    return np.vstack(arrays)

In [171]:
a= np.array([[0 ,1, 2 ,3 ,4]
    ,[5 ,6 ,7 ,8 ,9]])
b= np.array([[0 ,1, 2 ,3 ,4]
    ,[5 ,6 ,7 ,8 ,9]])
vertical_stack(a,b,b,c)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

###`Q-14:` Subtract the mean of each row from a matrix.

In [172]:
#code here

lst = np.random.randint(1, 100, size=(5,3))  # usual array 
print(lst.shape) # shape of the array 
# print(lst)
# a = np.mean((lst[0:1,:])) mean_value_cunnet_row =np.mean((lst[row:+row+1,:])) # using the slicing method 
print(lst)
print("")
size=0 
for row in range(len(lst)):
    mean_value_cunnet_row =np.mean((lst[row:+row+1,:]))
    print(mean_value_cunnet_row)
    for col in range(len(lst[row])):
        np.put(lst, [size], [lst[row][col] - mean_value_cunnet_row])
        size += 1      
print(lst)




(5, 3)
[[41 47 21]
 [ 2  5 43]
 [32 91 39]
 [82 27  1]
 [66 95 23]]

36.333333333333336
16.666666666666668
54.0
36.666666666666664
61.333333333333336
[[  4  10 -15]
 [-14 -11  26]
 [-22  37 -15]
 [ 45  -9 -35]
 [  4  33 -38]]


In [173]:


# work in flat index 

a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
np.put(a, [0, 4, 8], [10, 20, 30])
print(a)

[[10  2  3]
 [ 4 20  6]
 [ 7  8 30]]


In [174]:
# Using for loops with indices
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

for i in range(len(matrix)):
    
    for j in range(len(matrix[i])):
       print(j)

0
1
2
0
1
2
0
1
2


In [175]:
print(lst)

[[  4  10 -15]
 [-14 -11  26]
 [-22  37 -15]
 [ 45  -9 -35]
 [  4  33 -38]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

suing facning indexing and copy method 

In [176]:
a=np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])
b = a.copy()

b[-1]= a[[-2]]
b[-2]= a[[-1]]
print (b)



[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [177]:
a[[0,2,]] # rows passed

array([[1, 2, 3],
       [7, 8, 9]])

###`Q-16:` Replace odd elements in arrays with -1.

In [178]:

lst = np.random.randint(1, 1060, size=(5,3))
print(lst)
np.where(a%2 != 0,-1,a)


[[560  86 132]
 [755 112 329]
 [484 500 560]
 [341 547 820]
 [755 249 373]]


array([[-1,  2, -1],
       [ 4, -1,  6],
       [-1,  8, -1]])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X_{current value} - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


#### Data: [10, 20, 30, 40, 50]
 - min = 10, max = 50

 - 10 → (10-10)/(50-10) = 0/40   = 0
 - 20 → (20-10)/(50-10) = 10/40  = 0.25
 - 30 → (30-10)/(50-10) = 20/40  = 0.5
 - 40 → (40-10)/(50-10) = 30/40  = 0.75
 - 50 → (50-10)/(50-10) = 40/40  = 1

 - Result: [0, 0.25, 0.5, 0.75, 1]

In [179]:
arr1=np.random.randint(low=1, high=10000, size=8000).reshape(80,100)
print(arr1)
arr1_copy=arr1[:,0::2]
print(arr1_copy)

X_max=np.max(arr1_copy)
X_min =np.min(arr1_copy)
print(X_max,X_min)
for row in range(len(arr1_copy)):
    for col in range(len(arr1_copy[row])):
        up = arr1_copy[row][col]- X_min
        down = X_max-X_min
        final = up/down
        arr1_copy[row][col]= final 
print(arr1_copy)     

[[5687 6402 4172 ... 8925 9712 3588]
 [9123 4813 6743 ... 8568  324 6809]
 [4042 4221 4155 ... 6826 2171 9856]
 ...
 [6058 8381 8492 ... 3499 2398 3646]
 [4845  189  836 ... 3447 5394 9739]
 [6808  169 9577 ... 4911 4021  332]]
[[5687 4172 4831 ... 9734  548 9712]
 [9123 6743 9513 ... 5564 9345  324]
 [4042 4155 3746 ... 8695 3848 2171]
 ...
 [6058 8492 1716 ... 6984 8716 2398]
 [4845  836 4474 ... 1825 5015 5394]
 [6808 9577  903 ... 3014  360 4021]]
9997 7
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [180]:
print(arr1_copy)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


$$\large X_{normalized} = \frac{X_{current value} - X_{min}}{X_{max} - X_{min}}$$

In [181]:
arr1=np.random.randint(low=1, high=100, size=12).reshape(2,6)
print(arr1)
arr1_copy=arr1[:,0::2]
print(arr1_copy)

X_max=np.max(arr1_copy)
X_min =np.min(arr1_copy)
print(X_max,X_min)
for row in range(len(arr1_copy)):
    for col in range(len(arr1_copy[row])):
        up = arr1_copy[row][col]- X_min
        down = X_max-X_min
        final = up/down
        arr1_copy[row][col]= final 
print(arr1_copy)   

[[35 58 21 74 36 16]
 [20 11 95 22 74 43]]
[[35 21 36]
 [20 95 74]]
95 20
[[0 0 0]
 [0 1 0]]


In [182]:
#Code here
#slicing  
arr1[:,0::2]

array([[0, 0, 0],
       [0, 1, 0]], dtype=int32)

Faster method

In [185]:
import numpy as np

arr1 = np.random.randint(low=1, high=10000, size=8000).reshape(80, 100)
arr1_copy = arr1[:, 0::2]

X_max = np.max(arr1_copy)
X_min = np.min(arr1_copy)

# Vectorized normalization (entire array at once)
arr1_copy = (arr1_copy - X_min) / (X_max - X_min)

print(arr1_copy)

[[0.9629889  0.47924377 0.0190057  ... 0.19835951 0.37431229 0.69790937]
 [0.8586576  0.70931279 0.02710813 ... 0.01780534 0.52105632 0.83905172]
 [0.67020106 0.31469441 0.39641893 ... 0.92017605 0.64119236 0.43593078]
 ...
 [0.65159548 0.9809943  0.81274382 ... 0.01650495 0.54016205 0.3350005 ]
 [0.47214164 0.35240572 0.25147544 ... 0.82724817 0.9146744  0.19785936]
 [0.17645294 0.46874062 0.4823447  ... 0.94538362 0.38261478 0.54146244]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [183]:
#Code here

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [184]:
#code here

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.

**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```