In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('customer.csv')

In [4]:
df.sample(5)

,age,gender,review,education,purchased
4,16,Female,Average,UG,No
48,39,Female,Good,UG,Yes
7,60,Female,Poor,School,Yes
49,25,Female,Good,UG,No
18,19,Male,Good,School,No


In [7]:
df = df.iloc[:,2:] #[x0 :xN , 2 ownwardcolumn  : ownwards ]
# Row : column
# 2 will be included review 

In [8]:
df.head() # becasue of 2 its onward dfrom review 

,purchased
0,No
1,No
2,No
3,No
4,No


In [82]:
from sklearn.preprocessing import OrdinalEncoder

In [89]:
X_train

,review,education
16,Poor,UG
44,Average,UG
13,Average,School
48,Good,UG
42,Good,PG
38,Good,School
17,Poor,UG
4,Average,UG
5,Average,School
24,Average,PG


In [90]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [91]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [92]:
X_train = oe.transform(X_train)

In [93]:
X_train

array([[0., 1.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [1., 2.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [0., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 1.]])

In [86]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [87]:
X_train

array([[1., 2.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.]])

In [95]:
from sklearn.preprocessing import LabelEncoder

In [96]:
le = LabelEncoder()

In [97]:
le.fit(y_train)

LabelEncoder()

In [98]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [99]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [100]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1])