In [4]:
import numpy as np
import pandas as pd 


In [5]:
spoti = pd.read_csv('A:/spotify_churn_dataset.csv', nrows=1000) # till rows 100 
# low computation power

Take a deep look is there any link between gender and churn rate?   
Is it also with other to churn rate ? 
ALSO TAKE A DEEP LOOK FOR RANK LOOK !


In [7]:
spoti['gender'].value_counts()

gender
Female    341
Other     331
Male      328
Name: count, dtype: int64

# CHECK THE RANK FROM EACH COLUMN !

### Note that ordinal only works for string data.

In [8]:
cat_cols = spoti.select_dtypes(include=['object']).columns # object in pandas = Text/String columns
for col in cat_cols:
    print(f"\n{col}:")
    print(spoti[col].value_counts())


gender:
gender
Female    341
Other     331
Male      328
Name: count, dtype: int64

country:
country
DE    150
AU    133
US    131
UK    123
FR    122
IN    118
CA    113
PK    110
Name: count, dtype: int64

subscription_type:
subscription_type
Premium    294
Free       238
Family     236
Student    232
Name: count, dtype: int64

device_type:
device_type
Desktop    352
Web        331
Mobile     317
Name: count, dtype: int64


In [9]:
# SAME FOR THE 5TH MORE SIMPLE METHOD 
'''
for col in ['age','country','subscription_type','device_type','is_churned']:
    print(f"\n{col} counts:")
    print(spoti[col].value_counts().head(10))  # Top 10 values '''

'\nfor col in [\'age\',\'country\',\'subscription_type\',\'device_type\',\'is_churned\']:\n    print(f"\n{col} counts:")\n    print(spoti[col].value_counts().head(10))  # Top 10 values '

In [10]:
spoti['gender'].value_counts()

gender
Female    341
Other     331
Male      328
Name: count, dtype: int64

# now select the Rows 

In [11]:
spoti_Ilocked= spoti.iloc[:, [1, 4, 8]] 

In [12]:
spoti_Ilocked.sample(10)

,gender,subscription_type,device_type
30,Other,Premium,Web
953,Other,Family,Desktop
179,Female,Family,Desktop
33,Male,Family,Web
129,Male,Premium,Web
951,Male,Family,Desktop
730,Female,Family,Desktop
34,Female,Premium,Mobile
796,Female,Premium,Web
728,Other,Premium,Desktop


# As our data is shorted then we use train split test

In [13]:
from sklearn.model_selection import train_test_split 

In [14]:
spoti_Ilocked = spoti.iloc[:, [1, 4, 8]]  # Features
target = spoti.iloc[:, -1]                   # Target

X_train, X_test, Y_train, Y_test = train_test_split(
    spoti_Ilocked,  # Just variable, no '='
    target,         # Just variable, no '='
    test_size=0.2
)
#Separates features (X) from target (Y) for machine learning.

In [15]:
X_train

,gender,subscription_type,device_type
269,Female,Student,Mobile
312,Other,Family,Web
502,Other,Free,Web
54,Female,Family,Desktop
585,Female,Student,Web
...,...,...,...
731,Other,Family,Mobile
727,Other,Premium,Web
944,Male,Student,Desktop
548,Male,Student,Mobile


In [16]:
X_train['gender'].value_counts()

gender
Female    284
Male      261
Other     255
Name: count, dtype: int64

In [17]:
X_train['subscription_type'].value_counts()

subscription_type
Premium    221
Family     195
Student    194
Free       190
Name: count, dtype: int64

In [18]:
X_train['device_type'].value_counts()

device_type
Desktop    282
Web        262
Mobile     256
Name: count, dtype: int64

In [19]:
from sklearn.preprocessing import OrdinalEncoder


# Ranking the data 

In [20]:
# According to my data  from from 29,28,27
oe = OrdinalEncoder(
    categories=[['Other','Male','Female'],
                 ['Family','Student','Free','Premium' ],
                   [ 'Mobile', 'Web','Desktop'], ]
    )  # Fit the ordinal encoder on our training set X_train oe.fit(X_train)

# train ke upper fit karte

In [21]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Other', 'Male', 'Female'],
                           ['Family', 'Student', 'Free', 'Premium'],
                           ['Mobile', 'Web', 'Desktop']])

# Tranform dnon ke upper  karte hai 

In [22]:
X_train = oe.transform(X_train)
X_test= oe.transform(X_test)

# values are transformed 

In [23]:
X_train

array([[2., 1., 0.],
       [0., 0., 1.],
       [0., 2., 1.],
       ...,
       [1., 1., 2.],
       [1., 1., 0.],
       [2., 1., 1.]])

# 136 cell is verfifed and good 
matched data with 136<->128

# What it does:

a. Takes the encoding rules learned from training data  

b. Applies them to test data (using same categories/order)  

c. Returns encoded test data


|Before:      |After:     |
|:----          |-------------: |
|gender     subscription    | gender  subscription  |  
|   Female     Free         |    0       1      |  
|Female     Free            |       0       1  |  
|Male       Premium         |       1       3    |  
|Other      Student         |        2       0  |  

In [25]:
oe.categories_

[array(['Other', 'Male', 'Female'], dtype=object),
 array(['Family', 'Student', 'Free', 'Premium'], dtype=object),
 array(['Mobile', 'Web', 'Desktop'], dtype=object)]

In [26]:
X_train

array([[2., 1., 0.],
       [0., 0., 1.],
       [0., 2., 1.],
       ...,
       [1., 1., 2.],
       [1., 1., 0.],
       [2., 1., 1.]])

In [27]:
from sklearn.preprocessing import LabelEncoder

In [34]:
le = LabelEncoder() # randomly decide yes or kisko mille ga
# yes ko 0 mil sakta hai aur 1 same for no ke liye

In [35]:
le.fit(Y_train) # fit to tranning data

LabelEncoder()

In [38]:
print(le.classes_)

[0 1]


In [31]:
Y_train = le.transform(Y_train) 
Y_test = le.transform(Y_test)

In [32]:
Y_train

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,