In [55]:
array = [1,2,3,4,56,7,62]

# insetr and append 
location insert   
append last 

In [56]:
array.append(9)
print("The updated array & 9 at last :",array)
print("\n")
array.insert(1,0)
print("the location by instert",array)


The updated array & 9 at last : [1, 2, 3, 4, 56, 7, 62, 9]


the location by instert [1, 0, 2, 3, 4, 56, 7, 62, 9]


update vlaue 

In [1]:

nums = [1, 2, 3]

nums.insert(0, 99)    # Insert 99 at index 0 → [99, 1, 2, 3]
nums.insert(2, 50)    # Insert 50 at index 2 → [99, 1, 50, 2, 3]
nums.insert(len(nums), 100)  # Insert at end → [99, 1, 50, 2, 3, 100]

In [57]:
array[1]= 'ye le cid'
print('The updated value of the index 1 is :',array)

The updated value of the index 1 is : [1, 'ye le cid', 2, 3, 4, 56, 7, 62, 9]


# copy the arraY

In [58]:

array2 = array.copy()
print( array2)

print('\n')


# Equivalent to:
array2_oneByOne = []
for x in array:
    array2_oneByOne.append(x)
print(array2_oneByOne)
print('\n')




[1, 'ye le cid', 2, 3, 4, 56, 7, 62, 9]


[1, 'ye le cid', 2, 3, 4, 56, 7, 62, 9]




# memory level copy paste 

In [59]:
import copy

# Nested list example
array1 = [[1, 2], [3, 4]]

# SHALLOW COPY ([:], list(), copy())
array2 = array1[:]
array1[0][0] = 99
print(array2)  # [[99, 2], [3, 4]]  ← changed! Because inner list is shared
print(" when i  make change in the array 1 then also changed in array 2 ")
print(array1)


# DEEP COPY
array1 = [[1, 2], [3, 4]]
array3 = copy.deepcopy(array1)
array1[0][0] = 99
print(array3)  # [[1, 2], [3, 4]]  ← unchanged! Complete independent copy

[[99, 2], [3, 4]]
 when i  make change in the array 1 then also changed in array 2 
[[99, 2], [3, 4]]
[[1, 2], [3, 4]]


# Pop & Remove

In [60]:
array = [1,2,3,4,56,7,62]
array.pop(3) # if used without index then last one will poped out
print("\n")
print("The updated array after pop :",array,"56 is removed")
array.remove(2) # element will be remove from the list
print("array 2 element is removed from the list ",array)



The updated array after pop : [1, 2, 3, 56, 7, 62] 56 is removed
array 2 element is removed from the list  [1, 3, 56, 7, 62]


# slicing 

In [61]:
array = [1,2,3,4,56,7,62]
abc= array[2:-1] 
print("slicing : 3 se 7  ",abc)

slicing : 3 se 7   [3, 4, 56, 7]


# searching in array 

In [62]:
array = [1,2,3,4,56,7,62]
i = array.index(4) # element
print("\n")
print('The index of the searched value is :', i)



The index of the searched value is : 3


# numpy

In [71]:
import numpy as np 

In [72]:
np = [3,6,54,44,4,141,65,6,32,6,16.5, "loe"] # hertogenous data set
print(np)
print(type(np))
print(type(array))

[3, 6, 54, 44, 4, 141, 65, 6, 32, 6, 16.5, 'loe']
<class 'list'>
<class 'builtin_function_or_method'>


# Type casting

In [75]:
import numpy as np
arr = np.array([3,6,54,44,4,141,65,6,32,6,16.5], dtype=float)
print(arr)

[  3.    6.   54.   44.    4.  141.   65.    6.   32.    6.   16.5]


# linspace

In [81]:

arr = np.linspace(1, 10, 5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [84]:
arrrr = np.zeros((10,10))
print(arrrr   )

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
