In [1]:
import numpy as np

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [27]:
print(np.sort.__doc__)


Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and,
    in general, the actual implementation will vary with data type.
    The 'mergesort' option is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecified fields will still be used, in the order in which
    they co

In [28]:
# code here 
x = np.random.randint(0,100,size=12).reshape(4,3)
print(x ) 
print("")
x =np.sort(x)
print(x )


[[93 99 61]
 [94 20 38]
 [49 81 81]
 [73 36 19]]

[[61 93 99]
 [20 38 94]
 [49 81 81]
 [19 36 73]]



 - ii. based on 2nd column

 - axis 0  = column up to down each column 
 - axis 1  = row  left  to right each row 

In [29]:
x =np.sort(x, axis= )

SyntaxError: expected argument value expression (52190356.py, line 1)

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [ ]:
# code here

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
# code here
a = np.array([0 ,9 ,1 ,2 ,8,8])
a = np.unique(a)
a

array([0, 1, 2, 8, 9])

In [ ]:
a = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
a = np.unique(a, axis=0) # colum wise  
print( " colum wise \n",a) 
print("\n")
a = np.unique(a, axis=1) # row  
print( " colum wise \n",a)

 colum wise 
 [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]


 colum wise 
 [[0 1 2 8 9]
 [1 3 3 1 2]
 [1 3 8 8 2]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [ ]:

a = np.array([0 ,9 ,1 ,2 ,8,8])
a = np.flip(a)
a

array([8, 8, 2, 1, 9, 0])

 - if no attrubute is passed then 
 - Original a:
   [[15 93 96]
   [ 6 63 93]
   [92 90 74]
   [70 60 48]]

 - Flattened: [15, 93, 96, 6, 63, 93, 92, 90, 74, 70, 60, 48]
 - Reversed:  [48, 60, 70, 74, 90, 92, 93, 63, 6, 96, 93, 15]

In [40]:
a_mix = np.flip(a)
print(a_mix,"\n")

[[62 92 38 39]
 [63 92 30 18]
 [36 77 22 90]
 [44 98  6 15]] 



In [41]:
a = np.random.randint(0,100, size = 16).reshape(4,4)
print(a)
print("col wise flip\n")
a_row = np.flip(a,axis=0)# col 
print(a_row,"\n")

print("row wise flip\n")
a_col = np.flip(a,axis=1)# col 
print(a_col,"\n")


[[58 31 84 79]
 [22 62 12 18]
 [14 36 33 64]
 [12 30 33 97]]
col wise flip

[[12 30 33 97]
 [14 36 33 64]
 [22 62 12 18]
 [58 31 84 79]] 

row wise flip

[[79 84 31 58]
 [18 12 62 22]
 [64 33 36 14]
 [97 33 30 12]] 



In [42]:
a_col = np.flip(a,axis=(0,1))# col 
print(a_col,"\n")

[[97 33 30 12]
 [64 33 36 14]
 [18 12 62 22]
 [79 84 31 58]] 



### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [ ]:
arr = np.array( [[1,2,3,4,56],
                [10,-3,30,4,5],
                [3,2,5,-4,5],
                [9,7,3,6,5]] )
result=[]
x = 6
for row in range(len(arr)):
    for col in range(len(arr[row])):
        if x <arr[row][col]:
            result.append(row)
result = np.array(result)
result = np.unique(result)
result

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [23]:
# These arrays are given.
arr1 = np.random.randint(7,100,size = 5)
arr2 = np.random.randint(7,100,size = 4).reshape(2,2)
arr3 = np.random.randint(7,100,size = 8).reshape(2,2,2)

In [24]:
print(arr1)
arr1=np.ravel(arr1)
arr1

[34 43 23 43 98]


array([34, 43, 23, 43, 98], dtype=int32)

In [16]:
print(arr3)
arr3=np.ravel(arr3)
arr3

[[[55 56]
  [97 76]]

 [[81 20]
  [23 16]]]


array([55, 56, 97, 76, 81, 20, 23, 16], dtype=int32)

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [ ]:
# code here

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [ ]:
# code here

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [ ]:
# code here