In [4]:
import numpy as np

###`Q-1:` Find the nearest element in the array to a given integer.
```
Ex:-
a=23 and array - [10 17 24 31 38 45 52 59].
Nearest element is 24
```
Hint: Read about this function `argmin()`

In [5]:
# code here
arr = np.array([10 ,17 ,24 ,31 ,38 ,45 ,52, 59])
target = 25
idx = np.abs(arr - target) # if will make +ve interger each element i-- with out target 


print(idx) 

idx = np.abs(arr - target).argmin()
print(idx)

[15  8  1  6 13 20 27 34]
2


###`Q-2:` Replace multiples of 3 or 5 as 0 in the given array.
```
arr=[1 2 3 4 5 6 7 9]

result-> [1 2 0 4 0 0 7 0]
```


am = np.identity(3)
result = (am > 0).astype(int)
print(result)

In [6]:
arr = np.array([1 ,2 ,3 ,4 ,5 ,6 ,7 ,9])

arr = ((arr%3==0)|(arr%5==0)) # and doesn't work in numpy & here we | for or 
print(arr)

arr = ((arr%3==0)|(arr%5==0)).astype(int)
print(arr)



[False False  True False  True  True False  True]
[1 1 0 1 0 0 1 0]


In [7]:
arr = np.array([1 ,2 ,3 ,4 ,5 ,6 ,7 ,9])
for i in arr:
    if (((arr[i]%3==0)|(arr[i]%5==0))):
        arr[i]=0; 
    else :
        pass
print(arr)



[1 2 0 4 0 6 7 0]


###`Q-3:` Use Fancy Indexing.
1. Double the array elements at  given indexes
```
arr = np.arrange(10)
indexes = [0,3,4,9]
```
Result -> `[ 0  1  2  6  8  5  6  7  8 18]`

2. Using a given array make a different array as in below example
```
array = [1,2,3]
result array -> [1 1 1 2 2 2 3 3 3]
```
* Internal-repetion should be as length of the array.

Hint:
```
if a is an array
a = [2,4]
a[[1,1,0,1]] will result in-> [4 4 2 4]
```

In [8]:
arr = np.arange(10)
indexes = arr[0,3,4,9]

IndexError: too many indices for array: array is 1-dimensional, but 4 were indexed

###`Q-4:` Your are given an array which is havig some nan value. You job is to fill those nan values with most common element in the array.
```
arr=np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])

```

In [ ]:
# code here

### `Q-5:` Write a NumPy program

- to find the missing data in a given array. Return a boolean matrix.
- also try to fill those missing values with 0. For that, you can use `np.nan_to_num(a)`

```python
import numpy as np

np.array([[3, 2, np.nan, 1],
          [10, 12, 10, 9],
          [5, np.nan, 1, np.nan]])
          
```

a[~np.isnan(a)]

for i, row in enumerate(a):
    for j, val in enumerate(row):
        print(f"a[{i}][{j}] = {val}")


In [29]:
# code here

a = np.array([[3, 2, np.nan, 1], [10, 12, 10, 9], [5, np.nan, 1, np.nan]])



b = np.isnan(a) 
print(b) 

a[np.isnan(a)] = 0 # vector from 
print(a)


[[False False  True False]
 [False False False False]
 [False  True False  True]]
[[ 3.  2.  0.  1.]
 [10. 12. 10.  9.]
 [ 5.  0.  1.  0.]]


In [30]:

a = np.array([[3, 2, np.nan, 1], [10, 12, 10, 9], [5, np.nan, 1, np.nan]])

for i, row in enumerate(a):
    for j, val in enumerate(row):
        if np.isnan(val):  # Use np.isnan() not ==
            a[i][j] = 0

print(a)

[[ 3.  2.  0.  1.]
 [10. 12. 10.  9.]
 [ 5.  0.  1.  0.]]


###`Q-6:` Given two arrays, X and Y, construct the Cauchy matrix C.
`Cij =1/(xi - yj)`

http://en.wikipedia.org/wiki/Cauchy_matrix
```
x = numpy.array([1,2,3,4]).reshape((-1, 1)
y = numpy.array([5,6,7])
```

In [ ]:
# code here

###`Q-7:` Plot this below equation.

$$\large y = \frac{e^x - e^{-x}}{e^x + e^{-x}}$$

**Note: This equation is called tanh activation function. In deep learning, many times this function is used. If you find some difference between the sigmoid function and this tanh function, note that to your notebook.**

In [ ]:
# code here

### `Q-8:` Plot the below equation.

$$\large y = \sqrt{36 - (x - 4)^2} + 2$$

The range of x should be between -2 to 10. $x ∈ [-2, 10]$



In [ ]:
# code here

### `Q-9:` Write a program implement Boradcasting Rule to check if two array can be added or not.
Given tuples of shapes.
```
shape of a- (3,2,2)
shape of b- (2,2)

check_broadcast(a, b) -> return Boolean (True if can broadcasted, False other wise.)
```

In [ ]:
# code here