**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [4]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.
 
- null vector look like this 


- [0,0,0]
- [0,0,0]
- [0,0,0]


In [5]:
a = np.zeros((10))
a[3]=1
print(a)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [6]:
a = np.zeros((1,10))
a[0,3]=1
print(a)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


###`Q-2` Ask user to input two numbers a, b. 
- Write a program to generate a random array of shape (a, b)
- print the array and avg of the array.

In [7]:
d = np.random.randint(3, 11,size= (5,2))
d

array([[9, 4],
       [5, 3],
       [8, 6],
       [8, 6],
       [4, 6]], dtype=int32)

In [8]:
#Code here
a = 5 #int(input( "Enter the a "))
b = 5 #int(input( "Enter the b "))
arr = np.random.random( size=(5,4))*100
arr=np.average(arr)
print(arr)


54.7029431432455


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [9]:
#Code here
i = 5
j = 5
jj = np.zeros((i,j))
jj[ 0, : ] = 1 # oth column
jj[ : ,0 ]= 1
jj[-1, : ]=1
jj[ : , -1 ]=1




In [10]:
jj

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [11]:
#Code here
vec = np.linspace(0, 1, 12)[1:-1] #  

print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [12]:
#Code here
iden_matrix= np.ones((3,3)) 
iden_matrix[0, 1:3] = 0
iden_matrix[1, 0:3:2] = 0
iden_matrix[2, 0:2] = 0

iden_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# Method 1: Direct identity
iden_matrix1 = np.eye(3)

# Method 2: Using fill diagonal
iden_matrix2 = np.zeros((3,3))
np.fill_diagonal(iden_matrix2, 1)

# print
print(iden_matrix1,end="\n")
print(iden_matrix2,end="\n")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

just in case if u want to use random 

In [14]:
#1D
f = np.random.randint(0, 7, size=(5))
f

array([4, 2, 1, 2, 0], dtype=int32)

In [15]:
# 2d
f = np.random.random((1,5))

# radom need size
- not reshape
- .randint(1, 501, size=5) range size

In [16]:
arr = np.random.random( size=5)*10
arr

array([2.92315602, 6.04190881, 3.12479668, 8.18576111, 1.35256852])

In [17]:
arr = np.random.randint(1, 501, size=5)
arr

array([415, 269, 440, 384, 108], dtype=int32)

In [18]:
#Code here
f = np.arange(0,5).reshape((1,5))
g = np.arange(0,5).reshape((1,5))
h = np.arange(0,5).reshape((1,5))
np.vstack((f,g,h))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```
##### √[(x₁-x₂)² + (y₁-y₂)²]


In [19]:
#code here
points = np.random.randint(1, 100, size=(10,2))
given_point=np.array([[10,2]])
distance = np.zeros((1,10))

for i in range(len(points)):
    distance[0,i] = (   ((  points[i,0]-distance[0,0])**2) +   ((points[i,1]-distance[0,1])**2  ))**0.5
distance

array([[51.6139516 , 49.91812168, 36.70032844, 37.29389724, 31.422397  ,
        12.7800694 , 23.59440679, 34.38614588, 63.34036275,  4.38937016]])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

### Formula:
- z = 99 % 8 = 3
- y = (99 // 8) % 7 = 12 % 7 = 5  
- x = (99 // 8) // 7 = 12 // 7 = 1

In [20]:
#Code here
ii=np.random.randint(1,500,size=(6,7,8))
print(ii,end= "\n")

print(ii[1,5,3])

[[[256 442 256  18 121 195 407  74]
  [121 450 228 320 127 369 230  47]
  [485 135 385 185 101 311  21 357]
  [259 474 272 142 143 378 189  92]
  [463 198 497 439 103 387 336 446]
  [348 488 160 182 303 409 416  21]
  [438 108 210 446 115 458 259 168]]

 [[440 192 293 276 290  93 362 386]
  [141 139  13 421 443 183 113 261]
  [458  86 427 364 240 478 432 127]
  [ 99  84 380 469 324 201 356 207]
  [184 456 134 103 351 162 375 353]
  [403 202 410 175 237 128  42 474]
  [460 493 238 339 329 194  67 258]]

 [[435 221  18 496 391 299 288  20]
  [494 481 115 232 229 293  44 198]
  [139 270  79  27 289 188  94 108]
  [159 470 408 200 348 475 374 465]
  [486 306 491 483 249 380 217 343]
  [432 162  81 183  43 219 452 180]
  [428 331 166 334 423 419 427 137]]

 [[ 75  60  98  16 485 211 166 102]
  [390 220  20 143   7 489 388  82]
  [330 279 446 135 427 191 474 103]
  [207  27 462 367  46  11 479 272]
  [355 219 185 232 415 388 212  20]
  [467  64 135 428 202 308 162 135]
  [388 380 258 114  14

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [21]:
#Code here
q9= np.array([1 ,2 ,3 ,4 ,-8 ,-10])
q9[::-1] # start , stop , step up 





array([-10,  -8,   4,   3,   2,   1])

In [22]:
b = np.array([
            [1,2,3],
            [4,5,6]
            ])
print(b)

b[0]=b[0, ::-1]
b[1]=b[1, ::-1]

b



[[1 2 3]
 [4 5 6]]


array([[3, 2, 1],
       [6, 5, 4]])

#### np.flip(arr)

In [23]:
print(np.flip(b))
print(np.flip(q9))

[[4 5 6]
 [1 2 3]]
[-10  -8   4   3   2   1]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [24]:
#Code here
a= np.array([1,2,3,4])
count =0
for i in range(len(a)):
    count = count+1
count



4

In [25]:
# 2d 
b = np.array([
            [1,2,3],
            [4,5,6],
            [4,5,6],
            ])
row,col=b.shape
print( row, end= '\n' )
print( col, end= '\n' )
count = 0 
for i in range(row):
    for j in range(col):
        count = count+1
print(count)


3
3
9


In [26]:
# Final version  
b=np.random.randint(1,500,size=(6,7,8))
b.shape
layer ,row ,col = b.shape
count = 0
for i in range(layer):
    for j in range(row):
        for k in range(col):
            count = count+1
print(count)


336


In [27]:
count = np.prod(b.shape)
count

np.int64(336)

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$
z
https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

- e^ = math.e 
- z = array input [1,2,3,4,5,6,7,8]
 
$${e^{z₁}+e^{z₂}+e^{z₃}} = {\sum_{j=i}^{K}{e^{z_j}}}$$


- squares = sum(i**2 for i in range(1, 6))  
- 

In [28]:
import math
math.e

2.718281828459045

In [54]:
#Code here
input_arr=np.array([86.03331084,37.7285648 , 48.64908087, 87.16563062, 38.40852563, 37.20006318])

exp_arr = np.array([math.e ** x for x in input_arr])
deno =sum(exp_arr)
print("exp_arr", exp_arr,end ="\n ")

print()
print("deno",deno, end="\n" )
print()

result = exp_arr / deno

print(result)




exp_arr [2.31095856e+37 2.42832887e+16 1.34284959e+21 7.17054870e+37
 4.79303653e+16 1.43146972e+16]
 
deno 9.481507261792594e+37

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


In [ ]:
# exp_arr = np.array([math.e ** x for x in input_arr])
# exp_arr
exp_list = []
for x in input_arr:
    exp_list.append(math.e ** x)

array([1., 1., 1., 1., 1., 1.])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [63]:
a= np.array([[0 ,1, 2 ,3 ,4]
    ,[5 ,6 ,7 ,8 ,9]])
b= np.array([[0 ,1, 2 ,3 ,4]
    ,])
c = np.vstack((a,b))
print( a.shape)
print( b.shape)

dims = b.shape
dims

(2, 5)
(1, 5)


(1, 5)

#### *arrays 
- collects all arguments into a tuple

#### isinstance(arr, np.ndarray)
- Checks if 'arr' is a numpy array
-  Returns True if yes, False if no

In [ ]:
def vertical_stack(*arrays): # * arrays --> collects all arguments into a tuple
    for arr in arrays:
        if not isinstance(arr, np.ndarray):
            raise TypeError("All inputs must be numpy arrays")
    return np.vstack(arrays)

In [72]:
a= np.array([[0 ,1, 2 ,3 ,4]
    ,[5 ,6 ,7 ,8 ,9]])
b= np.array([[0 ,1, 2 ,3 ,4]
    ,[5 ,6 ,7 ,8 ,9]])
vertical_stack(a,b,b,c)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [82]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

In [83]:
#code here

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [84]:
#Code here

###`Q-16:` Replace odd elements in arrays with -1.

In [85]:
#Code here

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [86]:
#Code here

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [87]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2987, 4471, 9659,  535, 2798],
       [4700,  363, 3145,  501, 8025],
       [ 264, 3035, 8217, 5316, 6425],
       [4390, 4997, 7978, 7352, 8481],
       [6654,  693, 4745, 4796, 5418],
       [ 805, 6478, 5929, 6298, 2723],
       [8942, 2361, 5336, 3827, 3035],
       [8308, 8396, 1036, 3859, 2322]], dtype=int32)

In [88]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [89]:
#Code here

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [90]:
#code here