### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([52, 66, 17, 23, 71, 89, 90, 89, 39, 30, 46, 46, 14, 67, 11],
      dtype=int32)

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[67, 51, 16, 22],
       [48, 23, 80, 55],
       [12, 69, 75,  1],
       [91, 33, 43, 15],
       [75, 54,  5, 43],
       [62, 19, 34, 39]], dtype=int32)

#### sort
- sorted --> list return 
- np.sort --> numpy's array return


- numpy.sort( user_array, axis =1/0, kind= none , order = None)

- kind  --> give u diffrent sorting algo like, heap sort , merge sort , quick sort, etc 





In [5]:
np.sort(a)[::-1]

array([90, 89, 89, 71, 67, 66, 52, 46, 46, 39, 30, 23, 17, 14, 11],
      dtype=int32)

In [6]:
print(b)
print('\n')
print(np.sort(b,axis =0)) # 0 for column

[[67 51 16 22]
 [48 23 80 55]
 [12 69 75  1]
 [91 33 43 15]
 [75 54  5 43]
 [62 19 34 39]]


[[12 19  5  1]
 [48 23 16 15]
 [62 33 34 22]
 [67 51 43 39]
 [75 54 75 43]
 [91 69 80 55]]


In [7]:
print(b)
print('\n')
print(np.sort(b,axis =1)) # row wise 

[[67 51 16 22]
 [48 23 80 55]
 [12 69 75  1]
 [91 33 43 15]
 [75 54  5 43]
 [62 19 34 39]]


[[16 22 51 67]
 [23 48 55 80]
 [ 1 12 69 75]
 [15 33 43 91]
 [ 5 43 54 75]
 [19 34 39 62]]


### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [8]:
# code
np.append(a ,200) # sort it by the 

array([ 52,  66,  17,  23,  71,  89,  90,  89,  39,  30,  46,  46,  14,
        67,  11, 200])

In [16]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[38, 52, 48, 71],
       [96, 31, 75, 45],
       [81, 66, 34, 21],
       [58, 22, 68, 78],
       [41, 33, 33, 99],
       [24, 59, 42, 55]], dtype=int32)

# row wise add

In [20]:
c=np.append(b,np.ones((b.shape[0],1)),axis=1)
print(c)
print(c.shape[0])
print(c.shape[1])


[[38. 52. 48. 71.  1.]
 [96. 31. 75. 45.  1.]
 [81. 66. 34. 21.  1.]
 [58. 22. 68. 78.  1.]
 [41. 33. 33. 99.  1.]
 [24. 59. 42. 55.  1.]]
6
5


In [19]:
(b.shape[0],1)

(6, 1)

### col wise

In [ ]:


#np.append(b,np.ones((b.shape[0],1)),axis=0)
np.append(b, np.ones((1,4)), axis=0) 

array([[91., 67., 59., 28.],
       [14., 91., 37., 66.],
       [67., 26.,  5., 67.],
       [75., 51., 49., 50.],
       [46., 75., 30., 46.],
       [ 6., 32., 10., 13.],
       [ 1.,  1.,  1.,  1.]])

In [34]:
b.shape

(6, 4)

### adding random value to row 

## breakdown 


- 0        → low (minimum value, inclusive)
- 10       → high (maximum value, exclusive) → generates 0 to 9
-size     → shape of output array
- b.shape[0] → number of rows in b (e.g., 2)
- 4           → 4 columns

### No. shape[0] = rows, shape[1] = columns, shape[2] = depth (3D arrays).

## 2D array
- b.shape[0]  # rows
- b.shape[1]  # columns

## 3D array
- b.shape[0]  # depth
- b.shape[1]  # rows  
- b.shape[2]  # columns

In [42]:
np.append(b, np.random.randint(0, 10, size=(b.shape[0], 4)), axis=1)

array([[91, 67, 59, 28,  7,  1,  3,  4],
       [14, 91, 37, 66,  8,  6,  5,  1],
       [67, 26,  5, 67,  5,  8,  2,  7],
       [75, 51, 49, 50,  5,  5,  3,  5],
       [46, 75, 30, 46,  1,  8,  5,  8],
       [ 6, 32, 10, 13,  5,  2,  9,  3]], dtype=int32)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 1