### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([10, 49, 54, 56, 75,  4, 75, 14, 97, 76, 69, 49, 84, 50, 71],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[91,  5, 13, 60],
       [ 7, 45, 62, 73],
       [37, 81, 75, 13],
       [77, 17, 44, 67],
       [25, 58, 65, 94],
       [17, 20, 23, 20]], dtype=int32)

#### sort
- sorted --> list return 
- np.sort --> numpy's array return


- numpy.sort( user_array, axis =1/0, kind= none , order = None)

- kind  --> give u diffrent sorting algo like, heap sort , merge sort , quick sort, etc 





In [3]:
np.sort(a)[::-1]

array([97, 84, 76, 75, 75, 71, 69, 56, 54, 50, 49, 49, 14, 10,  4],
      dtype=int32)

In [4]:
print(b)
print('\n')
print(np.sort(b,axis =0)) # 0 for column

[[91  5 13 60]
 [ 7 45 62 73]
 [37 81 75 13]
 [77 17 44 67]
 [25 58 65 94]
 [17 20 23 20]]


[[ 7  5 13 13]
 [17 17 23 20]
 [25 20 44 60]
 [37 45 62 67]
 [77 58 65 73]
 [91 81 75 94]]


In [5]:
print(b)
print('\n')
print(np.sort(b,axis =1)) # row wise 

[[91  5 13 60]
 [ 7 45 62 73]
 [37 81 75 13]
 [77 17 44 67]
 [25 58 65 94]
 [17 20 23 20]]


[[ 5 13 60 91]
 [ 7 45 62 73]
 [13 37 75 81]
 [17 44 67 77]
 [25 58 65 94]
 [17 20 20 23]]


### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
# code
np.append(a ,200) # sort it by the 

array([ 10,  49,  54,  56,  75,   4,  75,  14,  97,  76,  69,  49,  84,
        50,  71, 200])

# Grenerate a new b 

In [7]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[37, 91, 57, 27],
       [38, 62, 90, 61],
       [53, 99, 70, 77],
       [48, 97, 43, 56],
       [ 5, 91, 10,  8],
       [ 9, 45, 86, 51]], dtype=int32)

## breakdown 


- 0        → low (minimum value, inclusive)
- 10       → high (maximum value, exclusive) → generates 0 to 9
-size     → shape of output array
- b.shape[0] → number of rows in b (e.g., 2)
- 4           → 4 columns

## breakdown 


- 0        → low (minimum value, inclusive)
- 10       → high (maximum value, exclusive) → generates 0 to 9
-size     → shape of output array
- b.shape[0] → number of rows in b (e.g., 2)
- 4           → 4 columns

### adding random value to row 

### No. shape[0] = rows, shape[1] = columns, shape[2] = depth (3D arrays).

## 2D array
- b.shape[0]  # rows
- b.shape[1]  # columns

## 3D array
- b.shape[0]  # depth
- b.shape[1]  # rows  
- b.shape[2]  # columns

# row wise add

In [8]:
print(b.shape)

(6, 4)


In [9]:
c=np.append(b,np.ones((b.shape[0],1)),axis=1)
print(c)
print(c.shape[0]) # rows 
print(c.shape[1])  # columns



[[37. 91. 57. 27.  1.]
 [38. 62. 90. 61.  1.]
 [53. 99. 70. 77.  1.]
 [48. 97. 43. 56.  1.]
 [ 5. 91. 10.  8.  1.]
 [ 9. 45. 86. 51.  1.]]
6
5


In [10]:

c.shape  # (row and col +1 )

(6, 5)

## col wise
what type of 
#### Axis 0 = rows (vertical), Axis 1 = columns (horizontal).
- array add (1, b.shape) = 1 x  4

In [11]:
b.shape[1]

4

In [12]:
# just changed the chape 

np.append(b,np.ones((1,b.shape[1])),axis=0) 


array([[37., 91., 57., 27.],
       [38., 62., 90., 61.],
       [53., 99., 70., 77.],
       [48., 97., 43., 56.],
       [ 5., 91., 10.,  8.],
       [ 9., 45., 86., 51.],
       [ 1.,  1.,  1.,  1.]])

In [13]:
b.shape

(6, 4)


- 0   → low (minimum value, inclusive)
- 100 → high (maximum value, exclusive) → numbers 0-99
- 25  → size (how many random numbers to generate)
- Creates 25 random integers between 0 and 99

In [14]:
d = np.random.randint(0,100,25).reshape(5,5)
d


array([[81, 69, 20,  5, 90],
       [43, 95, 68,  2, 30],
       [97,  6, 37, 31, 75],
       [49, 13, 96, 80, 80],
       [37, 80, 66, 76, 73]], dtype=int32)

In [15]:
d.sha

AttributeError: 'numpy.ndarray' object has no attribute 'sha'

In [ ]:
d.shape

(5, 5)

- b.shape[0]  # rows
- b.shape[1]  # columns

In [ ]:
d.shape[0]

-4

In [ ]:
e= d

In [ ]:
e

array([[68, 22,  0, 45, 75],
       [29, 58, 52, 21, 15],
       [59, 95, 98, 31, 16],
       [61, 44, 36, 17,  6],
       [37, 95, 38, 15, 67]], dtype=int32)

In [ ]:
e.shape[0]

5

In [ ]:
np.append(e, np.random.randint(0, 10, size=(e.shape[0], 1)), axis=1)
# 0 for column
# 5x 1  matrix add 

array([[68, 22,  0, 45, 75,  0],
       [29, 58, 52, 21, 15,  2],
       [59, 95, 98, 31, 16,  6],
       [61, 44, 36, 17,  6,  7],
       [37, 95, 38, 15, 67,  3]], dtype=int32)

In [ ]:
np.append(e, np.random.randint(0, 10, size=(e.shape[0], 2)), axis=1)
# 0 for column
# 5x 2  matrix add  last 2 columns  

array([[68, 22,  0, 45, 75,  6,  6],
       [29, 58, 52, 21, 15,  4,  5],
       [59, 95, 98, 31, 16,  1,  4],
       [61, 44, 36, 17,  6,  9,  5],
       [37, 95, 38, 15, 67,  9,  1]], dtype=int32)

# adding rows to the columns 

In [ ]:
f = d 
print(f .shape[0])
print(f .shape[1])
print (f)

5
5
[[68 22  0 45 75]
 [29 58 52 21 15]
 [59 95 98 31 16]
 [61 44 36 17  6]
 [37 95 38 15 67]]


In [ ]:
# np.append(b,np.ones((1,b.shape[1])),axis=0) 
np.append(f,np.ones((1,f.shape[1])),axis = 0 )

array([[68., 22.,  0., 45., 75.],
       [29., 58., 52., 21., 15.],
       [59., 95., 98., 31., 16.],
       [61., 44., 36., 17.,  6.],
       [37., 95., 38., 15., 67.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [ ]:
np.append(f,np.random.randint(-10,10,size = (1,f.shape[1])),axis = 0 )


array([[68, 22,  0, 45, 75],
       [29, 58, 52, 21, 15],
       [59, 95, 98, 31, 16],
       [61, 44, 36, 17,  6],
       [37, 95, 38, 15, 67],
       [-9,  6,  1, -4, -5]], dtype=int32)

### np.concatenate



- numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0) #axis = 1  column


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1) #axis = 1  column


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6,4,5,6,7,8,9,0])

In [ ]:
np.unique(e)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

use to convert vectors


In [ ]:
# code
a.shape

(15,)

In [ ]:
a

array([52, 66, 17, 23, 71, 89, 90, 89, 39, 30, 46, 46, 14, 67, 11],
      dtype=int32)

In [ ]:
print(np.expand_dims(a,axis=0).shape) # 1d--> 2d 
print(np.expand_dims(a,axis=0))

(1, 15)
[[52 66 17 23 71 89 90 89 39 30 46 46 14 67 11]]


In [ ]:
np.expand_dims(a,axis=1)

array([[52],
       [66],
       [17],
       [23],
       [71],
       [89],
       [90],
       [89],
       [39],
       [30],
       [46],
       [46],
       [14],
       [67],
       [11]], dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([52, 66, 17, 23, 71, 89, 90, 89, 39, 30, 46, 46, 14, 67, 11],
      dtype=int32)

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  4,  5,  6,  7, 13]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a) 

array([ 0,  0, 17, 23,  0,  0,  0,  0, 39, 30, 46, 46, 14,  0, 11],
      dtype=int32)

# check for the status boolean 
- a%2 == 0
- if true = 0
- if false = orginal digit 

In [ ]:
np.where(a%2 == 0,0,a) # 0=true, # a = false we are not going to replace it    


array([49,  0, 29,  9, 89,  0, 91,  0,  0,  0,  0,  0,  0,  0,  0],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [17]:
a

array([10, 49, 54, 56, 75,  4, 75, 14, 97, 76, 69, 49, 84, 50, 71],
      dtype=int32)

#### it will return only the index of larest number

In [18]:
np.argmax(a)

np.int64(8)

In [22]:
b

array([[37, 91, 57, 27],
       [38, 62, 90, 61],
       [53, 99, 70, 77],
       [48, 97, 43, 56],
       [ 5, 91, 10,  8],
       [ 9, 45, 86, 51]], dtype=int32)

In [32]:
b.shape


(6, 4)

In [26]:
np.argmax(b,axis=1) # row wise # 0 for colum wise

array([1, 2, 1, 1, 1, 2])

In [28]:
np.argmax(b,axis=0) # column wised 

array([2, 2, 1, 2])

### will return smallest item (position)

In [34]:
np.argmin(b,axis=0) # row 

array([4, 5, 4, 4])

In [33]:
b

array([[37, 91, 57, 27],
       [38, 62, 90, 61],
       [53, 99, 70, 77],
       [48, 97, 43, 56],
       [ 5, 91, 10,  8],
       [ 9, 45, 86, 51]], dtype=int32)

In [30]:
np.argmin(b,axis=1) 

array([3, 0, 0, 2, 0, 0])

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

a

In [35]:
a

array([10, 49, 54, 56, 75,  4, 75, 14, 97, 76, 69, 49, 84, 50, 71],
      dtype=int32)

-- ek ek kar kesum 

In [37]:
np.cumsum(a)

array([ 10,  59, 113, 169, 244, 248, 323, 337, 434, 510, 579, 628, 712,
       762, 833])

In [38]:
b

array([[37, 91, 57, 27],
       [38, 62, 90, 61],
       [53, 99, 70, 77],
       [48, 97, 43, 56],
       [ 5, 91, 10,  8],
       [ 9, 45, 86, 51]], dtype=int32)

In [39]:
np.cumsum(b,axis=1)

array([[ 37, 128, 185, 212],
       [ 38, 100, 190, 251],
       [ 53, 152, 222, 299],
       [ 48, 145, 188, 244],
       [  5,  96, 106, 114],
       [  9,  54, 140, 191]])

In [40]:
np.cumsum(b)

array([  37,  128,  185,  212,  250,  312,  402,  463,  516,  615,  685,
        762,  810,  907,  950, 1006, 1011, 1102, 1112, 1120, 1129, 1174,
       1260, 1311])

ek ek kar ke multiply


In [41]:
# np.cumprod
np.cumprod(a)

array([                  10,                  490,                26460,
                    1481760,            111132000,            444528000,
                33339600000,         466754400000,       45275176800000,
           3440913436800000,   237423027139200000, -6813015743888751616,
        -444256201659035648, -3766066009242230784, -9136269624264663040])

In [42]:
a

array([10, 49, 54, 56, 75,  4, 75, 14, 97, 76, 69, 49, 84, 50, 71],
      dtype=int32)

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [43]:
a

array([10, 49, 54, 56, 75,  4, 75, 14, 97, 76, 69, 49, 84, 50, 71],
      dtype=int32)

# this show up the person behind the 50
56 % percent log piche hai 

In [45]:
np.percentile(a,50)

np.float64(56.0)

In [46]:
np.median(a)

np.float64(56.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

-- frequecy count in given range
-- bin size 10 

 - 0-10 -> 4 number 
 - 11 -- 20 -> number

In [47]:
# code
a

array([10, 49, 54, 56, 75,  4, 75, 14, 97, 76, 69, 49, 84, 50, 71],
      dtype=int32)

#### bin size
 - ( 0 - 50 )   5 items 
 - ( 50 - 100)  10 item 

In [48]:
np.histogram(a,bins=[0,50,100])

(array([ 5, 10]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

- show colrealation between 2 quantity 
- means agar ek quantity badde tho dursra bhie badde ga
- lies (-1 <--> 1)

In [49]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

-- given array me mutiple item seach kar deta hai 

In [52]:
# code
a


array([10, 49, 54, 56, 75,  4, 75, 14, 97, 76, 69, 49, 84, 50, 71],
      dtype=int32)

In [54]:
items = [10,20]

a[np.isin(a,items)]

array([10], dtype=int32)

 ### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

-- reverse 0r mirror 

In [56]:
# code
a

array([10, 49, 54, 56, 75,  4, 75, 14, 97, 76, 69, 49, 84, 50, 71],
      dtype=int32)

In [57]:
np.flip(a)

array([71, 50, 84, 49, 69, 76, 97, 14, 75,  4, 75, 56, 54, 49, 10],
      dtype=int32)

In [58]:
b

array([[37, 91, 57, 27],
       [38, 62, 90, 61],
       [53, 99, 70, 77],
       [48, 97, 43, 56],
       [ 5, 91, 10,  8],
       [ 9, 45, 86, 51]], dtype=int32)

In [59]:
np.flip(b)

array([[51, 86, 45,  9],
       [ 8, 10, 91,  5],
       [56, 43, 97, 48],
       [77, 70, 99, 53],
       [61, 90, 62, 38],
       [27, 57, 91, 37]], dtype=int32)

In [60]:
np.flip(b, axis = 0)

array([[ 9, 45, 86, 51],
       [ 5, 91, 10,  8],
       [48, 97, 43, 56],
       [53, 99, 70, 77],
       [38, 62, 90, 61],
       [37, 91, 57, 27]], dtype=int32)

In [61]:
np.flip(b, axis = 1
)

array([[27, 57, 91, 37],
       [61, 90, 62, 38],
       [77, 70, 99, 53],
       [56, 43, 97, 48],
       [ 8, 10, 91,  5],
       [51, 86, 45,  9]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html


- u can change multiple items at ones 
- also perment changes

In [62]:
# code
a

array([10, 49, 54, 56, 75,  4, 75, 14, 97, 76, 69, 49, 84, 50, 71],
      dtype=int32)

In [68]:
np.put(a,[0,1],[111
                ,530])

In [69]:
a

array([111, 530,  54,  56,  75,   4,  75,  14,  97,  76,  69,  49,  84,
        50,  71], dtype=int32)

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [70]:
# code
a

array([111, 530,  54,  56,  75,   4,  75,  14,  97,  76,  69,  49,  84,
        50,  71], dtype=int32)

In [72]:
np.delete(a,[0,2,4])   # array -- index 0 ,index 1 ,index 2, 

array([530,  56,   4,  75,  14,  97,  76,  69,  49,  84,  50,  71],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [84]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n) # union calculate kar dedega

array([1, 2, 3, 4, 5, 6, 7])

In [85]:
np.intersect1d(m,n) #intersetion  avaibale in both 

array([3, 4, 5])

In [86]:
np.setdiff1d(n,m) # a me hai but be me nahi hai 

array([6, 7])

In [87]:
np.setxor1d(m,n)  # xor --> 

array([1, 2, 6, 7])

In [88]:
m[np.in1d(m,1)]

C:\Users\manis\AppData\Local\Temp\ipykernel_23224\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

-- range me value ko rakhta hai 

In [89]:
# code
a

array([111, 530,  54,  56,  75,   4,  75,  14,  97,  76,  69,  49,  84,
        50,  71], dtype=int32)

In [90]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 54, 56, 75, 25, 75, 25, 75, 75, 69, 49, 75, 50, 71],
      dtype=int32)