### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([52, 66, 17, 23, 71, 89, 90, 89, 39, 30, 46, 46, 14, 67, 11],
      dtype=int32)

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[67, 51, 16, 22],
       [48, 23, 80, 55],
       [12, 69, 75,  1],
       [91, 33, 43, 15],
       [75, 54,  5, 43],
       [62, 19, 34, 39]], dtype=int32)

#### sort
- sorted --> list return 
- np.sort --> numpy's array return


- numpy.sort( user_array, axis =1/0, kind= none , order = None)

- kind  --> give u diffrent sorting algo like, heap sort , merge sort , quick sort, etc 





In [5]:
np.sort(a)[::-1]

array([90, 89, 89, 71, 67, 66, 52, 46, 46, 39, 30, 23, 17, 14, 11],
      dtype=int32)

In [ ]:
print(b)
print('\n')
print(np.sort(b,axis =0)) # 0 for column

[[67 51 16 22]
 [48 23 80 55]
 [12 69 75  1]
 [91 33 43 15]
 [75 54  5 43]
 [62 19 34 39]]


[[12 19  5  1]
 [48 23 16 15]
 [62 33 34 22]
 [67 51 43 39]
 [75 54 75 43]
 [91 69 80 55]]


In [7]:
print(b)
print('\n')
print(np.sort(b,axis =1)) # row wise 

[[67 51 16 22]
 [48 23 80 55]
 [12 69 75  1]
 [91 33 43 15]
 [75 54  5 43]
 [62 19 34 39]]


[[16 22 51 67]
 [23 48 55 80]
 [ 1 12 69 75]
 [15 33 43 91]
 [ 5 43 54 75]
 [19 34 39 62]]


### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [8]:
# code
np.append(a ,200) # sort it by the 

array([ 52,  66,  17,  23,  71,  89,  90,  89,  39,  30,  46,  46,  14,
        67,  11, 200])

# Grenerate a new b 

In [21]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[14, 14,  9, 79],
       [78,  7, 52, 37],
       [87, 48,  3, 85],
       [45, 92, 18, 60],
       [92, 39, 18, 23],
       [55, 60, 62, 20]], dtype=int32)

## breakdown 


- 0        → low (minimum value, inclusive)
- 10       → high (maximum value, exclusive) → generates 0 to 9
-size     → shape of output array
- b.shape[0] → number of rows in b (e.g., 2)
- 4           → 4 columns

## breakdown 


- 0        → low (minimum value, inclusive)
- 10       → high (maximum value, exclusive) → generates 0 to 9
-size     → shape of output array
- b.shape[0] → number of rows in b (e.g., 2)
- 4           → 4 columns

### adding random value to row 

### No. shape[0] = rows, shape[1] = columns, shape[2] = depth (3D arrays).

## 2D array
- b.shape[0]  # rows
- b.shape[1]  # columns

## 3D array
- b.shape[0]  # depth
- b.shape[1]  # rows  
- b.shape[2]  # columns

# row wise add

In [27]:
print(b.shape)

(6, 4)


In [38]:
c=np.append(b,np.ones((b.shape[0],1)),axis=1)
print(c)
print(c.shape[0]) # rows 
print(c.shape[1])  # columns



[[14. 14.  9. 79.  1.]
 [78.  7. 52. 37.  1.]
 [87. 48.  3. 85.  1.]
 [45. 92. 18. 60.  1.]
 [92. 39. 18. 23.  1.]
 [55. 60. 62. 20.  1.]]
6
5


In [30]:

c.shape  # (row and col +1 )

(6, 5)

## col wise
what type of 
#### Axis 0 = rows (vertical), Axis 1 = columns (horizontal).
- array add (1, b.shape) = 1 x  4

In [41]:
b.shape[1]

4

In [42]:
# just changed the chape 

np.append(b,np.ones((1,b.shape[1])),axis=0) 


array([[14., 14.,  9., 79.],
       [78.,  7., 52., 37.],
       [87., 48.,  3., 85.],
       [45., 92., 18., 60.],
       [92., 39., 18., 23.],
       [55., 60., 62., 20.],
       [ 1.,  1.,  1.,  1.]])

In [43]:
b.shape

(6, 4)


- 0   → low (minimum value, inclusive)
- 100 → high (maximum value, exclusive) → numbers 0-99
- 25  → size (how many random numbers to generate)
- Creates 25 random integers between 0 and 99

In [ ]:
d = np.random.randint(0,100,25).reshape(5,5)
d


array([[68, 22,  0, 45, 75],
       [29, 58, 52, 21, 15],
       [59, 95, 98, 31, 16],
       [61, 44, 36, 17,  6],
       [37, 95, 38, 15, 67]], dtype=int32)

In [ ]:
d.sha

In [51]:
d.shape

(5, 5)

- b.shape[0]  # rows
- b.shape[1]  # columns

In [ ]:
d.shape[0]

-4

In [55]:
e= d

In [56]:
e

array([[68, 22,  0, 45, 75],
       [29, 58, 52, 21, 15],
       [59, 95, 98, 31, 16],
       [61, 44, 36, 17,  6],
       [37, 95, 38, 15, 67]], dtype=int32)

In [58]:
e.shape[0]

5

In [59]:
np.append(e, np.random.randint(0, 10, size=(e.shape[0], 1)), axis=1)
# 0 for column
# 5x 1  matrix add 

array([[68, 22,  0, 45, 75,  0],
       [29, 58, 52, 21, 15,  2],
       [59, 95, 98, 31, 16,  6],
       [61, 44, 36, 17,  6,  7],
       [37, 95, 38, 15, 67,  3]], dtype=int32)

In [61]:
np.append(e, np.random.randint(0, 10, size=(e.shape[0], 2)), axis=1)
# 0 for column
# 5x 2  matrix add  last 2 columns  

array([[68, 22,  0, 45, 75,  6,  6],
       [29, 58, 52, 21, 15,  4,  5],
       [59, 95, 98, 31, 16,  1,  4],
       [61, 44, 36, 17,  6,  9,  5],
       [37, 95, 38, 15, 67,  9,  1]], dtype=int32)

# adding rows to the columns 

In [63]:
f = d 
print(f .shape[0])
print(f .shape[1])
print (f)

5
5
[[68 22  0 45 75]
 [29 58 52 21 15]
 [59 95 98 31 16]
 [61 44 36 17  6]
 [37 95 38 15 67]]


In [74]:
# np.append(b,np.ones((1,b.shape[1])),axis=0) 
np.append(f,np.ones((1,f.shape[1])),axis = 0 )

array([[68., 22.,  0., 45., 75.],
       [29., 58., 52., 21., 15.],
       [59., 95., 98., 31., 16.],
       [61., 44., 36., 17.,  6.],
       [37., 95., 38., 15., 67.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [75]:
np.append(f,np.random.randint(-10,10,size = (1,f.shape[1])),axis = 0 )


array([[68, 22,  0, 45, 75],
       [29, 58, 52, 21, 15],
       [59, 95, 98, 31, 16],
       [61, 44, 36, 17,  6],
       [37, 95, 38, 15, 67],
       [-9,  6,  1, -4, -5]], dtype=int32)

### np.concatenate



- numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [76]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0) #axis = 1  column


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [78]:
np.concatenate((c,d),axis=1) #axis = 1  column


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [81]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6,4,5,6,7,8,9,0])

In [82]:
np.unique(e)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

use to convert vectors


In [83]:
# code
a.shape

(15,)

In [88]:
a

array([52, 66, 17, 23, 71, 89, 90, 89, 39, 30, 46, 46, 14, 67, 11],
      dtype=int32)

In [89]:
print(np.expand_dims(a,axis=0).shape) # 1d--> 2d 
print(np.expand_dims(a,axis=0))

(1, 15)
[[52 66 17 23 71 89 90 89 39 30 46 46 14 67 11]]


In [90]:
np.expand_dims(a,axis=1)

array([[52],
       [66],
       [17],
       [23],
       [71],
       [89],
       [90],
       [89],
       [39],
       [30],
       [46],
       [46],
       [14],
       [67],
       [11]], dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [91]:
a

array([52, 66, 17, 23, 71, 89, 90, 89, 39, 30, 46, 46, 14, 67, 11],
      dtype=int32)

In [93]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  4,  5,  6,  7, 13]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a) 

array([ 0,  0, 17, 23,  0,  0,  0,  0, 39, 30, 46, 46, 14,  0, 11],
      dtype=int32)

# check for the status boolean 
- a%2 == 0
- if true = 0
- if false = orginal digit 

In [98]:
np.where(a%2 == 0,0,a) # 0=true, # a = false we are not going to replace it    


array([ 0,  0, 17, 23, 71, 89,  0, 89, 39,  0,  0,  0,  0, 67, 11],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html